// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: fintcart/auth/v1/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { OpResult } from "../../common/v1/common";

export const protobufPackage = "fintcart.auth.v1";

export interface UserRef {
  user_id: string;
}

export interface CreateCredentialRequest {
  user_id: string;
  email: string;
  /** se hashea con Argon2id; nunca se persiste/loguea en claro */
  password: string;
}

/**
 * Token de verificación de correo en claro. Solo viaja de Auth al correo del
 * titular, pasando por el Orquestador y el bus; en `auth_db` únicamente se guarda
 * su hash, igual que con una contraseña.
 */
export interface VerificationToken {
  token: string;
  /** RFC-3339 UTC; caducado deja de activar (FR-002) */
  expires_at: string;
}

export interface ActivateCredentialRequest {
  user_id: string;
  /**
   * OBLIGATORIO. Es la ÚNICA prueba de que quien verifica controla el buzón: sin
   * él, conocer un user_id —que viaja en cada evento de auditoría— bastaría para
   * activar la cuenta de otro, y el correo de verificación no comprobaría nada.
   */
  verification_token: string;
}

export interface ValidateCredentialsRequest {
  email: string;
  password: string;
}

export interface ValidateCredentialsResponse {
  valid: boolean;
  user_id: string;
  email_verified: boolean;
  /** pending_verification | active | anonymized */
  login_status: string;
}

export interface IssueAuthCodeRequest {
  user_id: string;
  client_id: string;
  redirect_uri: string;
  code_challenge: string;
  /** "S256" */
  code_challenge_method: string;
  scopes: string[];
}

export interface IssueAuthCodeResponse {
  code: string;
}

export interface ExchangeCodeRequest {
  code: string;
  /** PKCE */
  code_verifier: string;
  client_id: string;
  redirect_uri: string;
}

export interface RefreshTokenRequest {
  refresh_token: string;
}

export interface TokenResponse {
  /** JWT firmado */
  access_token: string;
  /** rotado */
  refresh_token: string;
  /** "Bearer" */
  token_type: string;
  /** segundos */
  expires_in: number;
}

export interface RevokeRequest {
  /** access o refresh */
  token: string;
  token_type_hint: string;
}

export interface ChangePasswordRequest {
  user_id: string;
  /** se verifica contra el hash vigente */
  current_password: string;
  /** se hashea con Argon2id; nunca se persiste/loguea en claro */
  new_password: string;
}

export interface IntrospectRequest {
  access_token: string;
}

export interface IntrospectResponse {
  /** false si está en blacklist o expirado */
  active: boolean;
  user_id: string;
  roles: string[];
  jti: string;
  exp: string;
}

function createBaseUserRef(): UserRef {
  return { user_id: "" };
}

export const UserRef: MessageFns<UserRef> = {
  encode(message: UserRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRef {
    return { user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "" };
  },

  toJSON(message: UserRef): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRef>, I>>(base?: I): UserRef {
    return UserRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRef>, I>>(object: I): UserRef {
    const message = createBaseUserRef();
    message.user_id = object.user_id ?? "";
    return message;
  },
};

function createBaseCreateCredentialRequest(): CreateCredentialRequest {
  return { user_id: "", email: "", password: "" };
}

export const CreateCredentialRequest: MessageFns<CreateCredentialRequest> = {
  encode(message: CreateCredentialRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(26).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCredentialRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCredentialRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCredentialRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: CreateCredentialRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCredentialRequest>, I>>(base?: I): CreateCredentialRequest {
    return CreateCredentialRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCredentialRequest>, I>>(object: I): CreateCredentialRequest {
    const message = createBaseCreateCredentialRequest();
    message.user_id = object.user_id ?? "";
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseVerificationToken(): VerificationToken {
  return { token: "", expires_at: "" };
}

export const VerificationToken: MessageFns<VerificationToken> = {
  encode(message: VerificationToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.expires_at !== "") {
      writer.uint32(18).string(message.expires_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerificationToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerificationToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expires_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerificationToken {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      expires_at: isSet(object.expires_at) ? globalThis.String(object.expires_at) : "",
    };
  },

  toJSON(message: VerificationToken): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.expires_at !== "") {
      obj.expires_at = message.expires_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerificationToken>, I>>(base?: I): VerificationToken {
    return VerificationToken.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerificationToken>, I>>(object: I): VerificationToken {
    const message = createBaseVerificationToken();
    message.token = object.token ?? "";
    message.expires_at = object.expires_at ?? "";
    return message;
  },
};

function createBaseActivateCredentialRequest(): ActivateCredentialRequest {
  return { user_id: "", verification_token: "" };
}

export const ActivateCredentialRequest: MessageFns<ActivateCredentialRequest> = {
  encode(message: ActivateCredentialRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.verification_token !== "") {
      writer.uint32(18).string(message.verification_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActivateCredentialRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActivateCredentialRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.verification_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActivateCredentialRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      verification_token: isSet(object.verification_token) ? globalThis.String(object.verification_token) : "",
    };
  },

  toJSON(message: ActivateCredentialRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.verification_token !== "") {
      obj.verification_token = message.verification_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActivateCredentialRequest>, I>>(base?: I): ActivateCredentialRequest {
    return ActivateCredentialRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActivateCredentialRequest>, I>>(object: I): ActivateCredentialRequest {
    const message = createBaseActivateCredentialRequest();
    message.user_id = object.user_id ?? "";
    message.verification_token = object.verification_token ?? "";
    return message;
  },
};

function createBaseValidateCredentialsRequest(): ValidateCredentialsRequest {
  return { email: "", password: "" };
}

export const ValidateCredentialsRequest: MessageFns<ValidateCredentialsRequest> = {
  encode(message: ValidateCredentialsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateCredentialsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateCredentialsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateCredentialsRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: ValidateCredentialsRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateCredentialsRequest>, I>>(base?: I): ValidateCredentialsRequest {
    return ValidateCredentialsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateCredentialsRequest>, I>>(object: I): ValidateCredentialsRequest {
    const message = createBaseValidateCredentialsRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseValidateCredentialsResponse(): ValidateCredentialsResponse {
  return { valid: false, user_id: "", email_verified: false, login_status: "" };
}

export const ValidateCredentialsResponse: MessageFns<ValidateCredentialsResponse> = {
  encode(message: ValidateCredentialsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.valid !== false) {
      writer.uint32(8).bool(message.valid);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.email_verified !== false) {
      writer.uint32(24).bool(message.email_verified);
    }
    if (message.login_status !== "") {
      writer.uint32(34).string(message.login_status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateCredentialsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateCredentialsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.valid = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.email_verified = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.login_status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateCredentialsResponse {
    return {
      valid: isSet(object.valid) ? globalThis.Boolean(object.valid) : false,
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      email_verified: isSet(object.email_verified) ? globalThis.Boolean(object.email_verified) : false,
      login_status: isSet(object.login_status) ? globalThis.String(object.login_status) : "",
    };
  },

  toJSON(message: ValidateCredentialsResponse): unknown {
    const obj: any = {};
    if (message.valid !== false) {
      obj.valid = message.valid;
    }
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.email_verified !== false) {
      obj.email_verified = message.email_verified;
    }
    if (message.login_status !== "") {
      obj.login_status = message.login_status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateCredentialsResponse>, I>>(base?: I): ValidateCredentialsResponse {
    return ValidateCredentialsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateCredentialsResponse>, I>>(object: I): ValidateCredentialsResponse {
    const message = createBaseValidateCredentialsResponse();
    message.valid = object.valid ?? false;
    message.user_id = object.user_id ?? "";
    message.email_verified = object.email_verified ?? false;
    message.login_status = object.login_status ?? "";
    return message;
  },
};

function createBaseIssueAuthCodeRequest(): IssueAuthCodeRequest {
  return { user_id: "", client_id: "", redirect_uri: "", code_challenge: "", code_challenge_method: "", scopes: [] };
}

export const IssueAuthCodeRequest: MessageFns<IssueAuthCodeRequest> = {
  encode(message: IssueAuthCodeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.client_id !== "") {
      writer.uint32(18).string(message.client_id);
    }
    if (message.redirect_uri !== "") {
      writer.uint32(26).string(message.redirect_uri);
    }
    if (message.code_challenge !== "") {
      writer.uint32(34).string(message.code_challenge);
    }
    if (message.code_challenge_method !== "") {
      writer.uint32(42).string(message.code_challenge_method);
    }
    for (const v of message.scopes) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IssueAuthCodeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIssueAuthCodeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.client_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.redirect_uri = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.code_challenge = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.code_challenge_method = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IssueAuthCodeRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      client_id: isSet(object.client_id) ? globalThis.String(object.client_id) : "",
      redirect_uri: isSet(object.redirect_uri) ? globalThis.String(object.redirect_uri) : "",
      code_challenge: isSet(object.code_challenge) ? globalThis.String(object.code_challenge) : "",
      code_challenge_method: isSet(object.code_challenge_method) ? globalThis.String(object.code_challenge_method) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: IssueAuthCodeRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.client_id !== "") {
      obj.client_id = message.client_id;
    }
    if (message.redirect_uri !== "") {
      obj.redirect_uri = message.redirect_uri;
    }
    if (message.code_challenge !== "") {
      obj.code_challenge = message.code_challenge;
    }
    if (message.code_challenge_method !== "") {
      obj.code_challenge_method = message.code_challenge_method;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IssueAuthCodeRequest>, I>>(base?: I): IssueAuthCodeRequest {
    return IssueAuthCodeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IssueAuthCodeRequest>, I>>(object: I): IssueAuthCodeRequest {
    const message = createBaseIssueAuthCodeRequest();
    message.user_id = object.user_id ?? "";
    message.client_id = object.client_id ?? "";
    message.redirect_uri = object.redirect_uri ?? "";
    message.code_challenge = object.code_challenge ?? "";
    message.code_challenge_method = object.code_challenge_method ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    return message;
  },
};

function createBaseIssueAuthCodeResponse(): IssueAuthCodeResponse {
  return { code: "" };
}

export const IssueAuthCodeResponse: MessageFns<IssueAuthCodeResponse> = {
  encode(message: IssueAuthCodeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IssueAuthCodeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIssueAuthCodeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IssueAuthCodeResponse {
    return { code: isSet(object.code) ? globalThis.String(object.code) : "" };
  },

  toJSON(message: IssueAuthCodeResponse): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IssueAuthCodeResponse>, I>>(base?: I): IssueAuthCodeResponse {
    return IssueAuthCodeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IssueAuthCodeResponse>, I>>(object: I): IssueAuthCodeResponse {
    const message = createBaseIssueAuthCodeResponse();
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseExchangeCodeRequest(): ExchangeCodeRequest {
  return { code: "", code_verifier: "", client_id: "", redirect_uri: "" };
}

export const ExchangeCodeRequest: MessageFns<ExchangeCodeRequest> = {
  encode(message: ExchangeCodeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.code_verifier !== "") {
      writer.uint32(18).string(message.code_verifier);
    }
    if (message.client_id !== "") {
      writer.uint32(26).string(message.client_id);
    }
    if (message.redirect_uri !== "") {
      writer.uint32(34).string(message.redirect_uri);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeCodeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeCodeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code_verifier = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.client_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.redirect_uri = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeCodeRequest {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      code_verifier: isSet(object.code_verifier) ? globalThis.String(object.code_verifier) : "",
      client_id: isSet(object.client_id) ? globalThis.String(object.client_id) : "",
      redirect_uri: isSet(object.redirect_uri) ? globalThis.String(object.redirect_uri) : "",
    };
  },

  toJSON(message: ExchangeCodeRequest): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.code_verifier !== "") {
      obj.code_verifier = message.code_verifier;
    }
    if (message.client_id !== "") {
      obj.client_id = message.client_id;
    }
    if (message.redirect_uri !== "") {
      obj.redirect_uri = message.redirect_uri;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeCodeRequest>, I>>(base?: I): ExchangeCodeRequest {
    return ExchangeCodeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeCodeRequest>, I>>(object: I): ExchangeCodeRequest {
    const message = createBaseExchangeCodeRequest();
    message.code = object.code ?? "";
    message.code_verifier = object.code_verifier ?? "";
    message.client_id = object.client_id ?? "";
    message.redirect_uri = object.redirect_uri ?? "";
    return message;
  },
};

function createBaseRefreshTokenRequest(): RefreshTokenRequest {
  return { refresh_token: "" };
}

export const RefreshTokenRequest: MessageFns<RefreshTokenRequest> = {
  encode(message: RefreshTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refresh_token !== "") {
      writer.uint32(10).string(message.refresh_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refresh_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenRequest {
    return { refresh_token: isSet(object.refresh_token) ? globalThis.String(object.refresh_token) : "" };
  },

  toJSON(message: RefreshTokenRequest): unknown {
    const obj: any = {};
    if (message.refresh_token !== "") {
      obj.refresh_token = message.refresh_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(base?: I): RefreshTokenRequest {
    return RefreshTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(object: I): RefreshTokenRequest {
    const message = createBaseRefreshTokenRequest();
    message.refresh_token = object.refresh_token ?? "";
    return message;
  },
};

function createBaseTokenResponse(): TokenResponse {
  return { access_token: "", refresh_token: "", token_type: "", expires_in: 0 };
}

export const TokenResponse: MessageFns<TokenResponse> = {
  encode(message: TokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.access_token !== "") {
      writer.uint32(10).string(message.access_token);
    }
    if (message.refresh_token !== "") {
      writer.uint32(18).string(message.refresh_token);
    }
    if (message.token_type !== "") {
      writer.uint32(26).string(message.token_type);
    }
    if (message.expires_in !== 0) {
      writer.uint32(32).int32(message.expires_in);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refresh_token = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.token_type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.expires_in = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenResponse {
    return {
      access_token: isSet(object.access_token) ? globalThis.String(object.access_token) : "",
      refresh_token: isSet(object.refresh_token) ? globalThis.String(object.refresh_token) : "",
      token_type: isSet(object.token_type) ? globalThis.String(object.token_type) : "",
      expires_in: isSet(object.expires_in) ? globalThis.Number(object.expires_in) : 0,
    };
  },

  toJSON(message: TokenResponse): unknown {
    const obj: any = {};
    if (message.access_token !== "") {
      obj.access_token = message.access_token;
    }
    if (message.refresh_token !== "") {
      obj.refresh_token = message.refresh_token;
    }
    if (message.token_type !== "") {
      obj.token_type = message.token_type;
    }
    if (message.expires_in !== 0) {
      obj.expires_in = Math.round(message.expires_in);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TokenResponse>, I>>(base?: I): TokenResponse {
    return TokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TokenResponse>, I>>(object: I): TokenResponse {
    const message = createBaseTokenResponse();
    message.access_token = object.access_token ?? "";
    message.refresh_token = object.refresh_token ?? "";
    message.token_type = object.token_type ?? "";
    message.expires_in = object.expires_in ?? 0;
    return message;
  },
};

function createBaseRevokeRequest(): RevokeRequest {
  return { token: "", token_type_hint: "" };
}

export const RevokeRequest: MessageFns<RevokeRequest> = {
  encode(message: RevokeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.token_type_hint !== "") {
      writer.uint32(18).string(message.token_type_hint);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RevokeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRevokeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token_type_hint = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RevokeRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      token_type_hint: isSet(object.token_type_hint) ? globalThis.String(object.token_type_hint) : "",
    };
  },

  toJSON(message: RevokeRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.token_type_hint !== "") {
      obj.token_type_hint = message.token_type_hint;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RevokeRequest>, I>>(base?: I): RevokeRequest {
    return RevokeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RevokeRequest>, I>>(object: I): RevokeRequest {
    const message = createBaseRevokeRequest();
    message.token = object.token ?? "";
    message.token_type_hint = object.token_type_hint ?? "";
    return message;
  },
};

function createBaseChangePasswordRequest(): ChangePasswordRequest {
  return { user_id: "", current_password: "", new_password: "" };
}

export const ChangePasswordRequest: MessageFns<ChangePasswordRequest> = {
  encode(message: ChangePasswordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.current_password !== "") {
      writer.uint32(18).string(message.current_password);
    }
    if (message.new_password !== "") {
      writer.uint32(26).string(message.new_password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangePasswordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangePasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.current_password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.new_password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangePasswordRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      current_password: isSet(object.current_password) ? globalThis.String(object.current_password) : "",
      new_password: isSet(object.new_password) ? globalThis.String(object.new_password) : "",
    };
  },

  toJSON(message: ChangePasswordRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.current_password !== "") {
      obj.current_password = message.current_password;
    }
    if (message.new_password !== "") {
      obj.new_password = message.new_password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangePasswordRequest>, I>>(base?: I): ChangePasswordRequest {
    return ChangePasswordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangePasswordRequest>, I>>(object: I): ChangePasswordRequest {
    const message = createBaseChangePasswordRequest();
    message.user_id = object.user_id ?? "";
    message.current_password = object.current_password ?? "";
    message.new_password = object.new_password ?? "";
    return message;
  },
};

function createBaseIntrospectRequest(): IntrospectRequest {
  return { access_token: "" };
}

export const IntrospectRequest: MessageFns<IntrospectRequest> = {
  encode(message: IntrospectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.access_token !== "") {
      writer.uint32(10).string(message.access_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IntrospectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntrospectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IntrospectRequest {
    return { access_token: isSet(object.access_token) ? globalThis.String(object.access_token) : "" };
  },

  toJSON(message: IntrospectRequest): unknown {
    const obj: any = {};
    if (message.access_token !== "") {
      obj.access_token = message.access_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IntrospectRequest>, I>>(base?: I): IntrospectRequest {
    return IntrospectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IntrospectRequest>, I>>(object: I): IntrospectRequest {
    const message = createBaseIntrospectRequest();
    message.access_token = object.access_token ?? "";
    return message;
  },
};

function createBaseIntrospectResponse(): IntrospectResponse {
  return { active: false, user_id: "", roles: [], jti: "", exp: "0" };
}

export const IntrospectResponse: MessageFns<IntrospectResponse> = {
  encode(message: IntrospectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.active !== false) {
      writer.uint32(8).bool(message.active);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    for (const v of message.roles) {
      writer.uint32(26).string(v!);
    }
    if (message.jti !== "") {
      writer.uint32(34).string(message.jti);
    }
    if (message.exp !== "0") {
      writer.uint32(40).int64(message.exp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IntrospectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntrospectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.roles.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.jti = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.exp = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IntrospectResponse {
    return {
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      roles: globalThis.Array.isArray(object?.roles) ? object.roles.map((e: any) => globalThis.String(e)) : [],
      jti: isSet(object.jti) ? globalThis.String(object.jti) : "",
      exp: isSet(object.exp) ? globalThis.String(object.exp) : "0",
    };
  },

  toJSON(message: IntrospectResponse): unknown {
    const obj: any = {};
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.roles?.length) {
      obj.roles = message.roles;
    }
    if (message.jti !== "") {
      obj.jti = message.jti;
    }
    if (message.exp !== "0") {
      obj.exp = message.exp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IntrospectResponse>, I>>(base?: I): IntrospectResponse {
    return IntrospectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IntrospectResponse>, I>>(object: I): IntrospectResponse {
    const message = createBaseIntrospectResponse();
    message.active = object.active ?? false;
    message.user_id = object.user_id ?? "";
    message.roles = object.roles?.map((e) => e) || [];
    message.jti = object.jti ?? "";
    message.exp = object.exp ?? "0";
    return message;
  },
};

/**
 * Servidor de Autenticación (Go). Autoridad de identidad (Constitución Principio VII).
 * OAuth2 Authorization Code + PKCE (SPA) y Client Credentials (M2M). JWT firmados;
 * revocación vía blacklist en Redis. Expone gRPC SOLO a servicios internos
 * (el flujo OAuth de cara al usuario lo traduce el API Gateway en el borde REST).
 */
export type AuthServiceService = typeof AuthServiceService;
export const AuthServiceService = {
  /**
   * Paso de la Saga de registro (research D-04): crea la credencial en estado
   * pending_verification. Idempotente por user_id.
   */
  createCredential: {
    path: "/fintcart.auth.v1.AuthService/CreateCredential",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateCredentialRequest) => Buffer.from(CreateCredentialRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreateCredentialRequest.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
  /**
   * Emite (o REEMITE) el token de verificación de correo.
   *
   * Lo invoca el paso de la saga de registro que produce el evento `user.registered`,
   * y el reenvío del correo cuando el enlace caduca (FR-002). Cada llamada SUSTITUYE
   * al token anterior: un reenvío tiene que invalidar el enlace previo, porque si no
   * un correo interceptado seguiría sirviendo indefinidamente.
   *
   * El valor en claro se devuelve UNA sola vez y no se puede volver a consultar: en
   * la base solo queda su hash. Quien pierda la respuesta tiene que reemitir.
   */
  issueVerificationToken: {
    path: "/fintcart.auth.v1.AuthService/IssueVerificationToken",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserRef) => Buffer.from(UserRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserRef.decode(value),
    responseSerialize: (value: VerificationToken) => Buffer.from(VerificationToken.encode(value).finish()),
    responseDeserialize: (value: Buffer) => VerificationToken.decode(value),
  },
  /** Activa la credencial tras verificación de correo (Saga de verificación). */
  activateCredential: {
    path: "/fintcart.auth.v1.AuthService/ActivateCredential",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ActivateCredentialRequest) =>
      Buffer.from(ActivateCredentialRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ActivateCredentialRequest.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
  /** Valida correo+contraseña durante el login del Authorization Code flow. */
  validateCredentials: {
    path: "/fintcart.auth.v1.AuthService/ValidateCredentials",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateCredentialsRequest) =>
      Buffer.from(ValidateCredentialsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ValidateCredentialsRequest.decode(value),
    responseSerialize: (value: ValidateCredentialsResponse) =>
      Buffer.from(ValidateCredentialsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ValidateCredentialsResponse.decode(value),
  },
  /** Emite un authorization_code (PKCE) tras autenticación exitosa. */
  issueAuthorizationCode: {
    path: "/fintcart.auth.v1.AuthService/IssueAuthorizationCode",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: IssueAuthCodeRequest) => Buffer.from(IssueAuthCodeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => IssueAuthCodeRequest.decode(value),
    responseSerialize: (value: IssueAuthCodeResponse) => Buffer.from(IssueAuthCodeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => IssueAuthCodeResponse.decode(value),
  },
  /** Intercambia authorization_code + code_verifier por tokens. */
  exchangeCode: {
    path: "/fintcart.auth.v1.AuthService/ExchangeCode",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ExchangeCodeRequest) => Buffer.from(ExchangeCodeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ExchangeCodeRequest.decode(value),
    responseSerialize: (value: TokenResponse) => Buffer.from(TokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => TokenResponse.decode(value),
  },
  /** Rota un refresh token (rotación obligatoria, research D-05). */
  refreshToken: {
    path: "/fintcart.auth.v1.AuthService/RefreshToken",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RefreshTokenRequest) => Buffer.from(RefreshTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RefreshTokenRequest.decode(value),
    responseSerialize: (value: TokenResponse) => Buffer.from(TokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => TokenResponse.decode(value),
  },
  /** Revoca un token (logout con efecto inmediato, FR-004): añade jti a blacklist. */
  revoke: {
    path: "/fintcart.auth.v1.AuthService/Revoke",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RevokeRequest) => Buffer.from(RevokeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RevokeRequest.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
  /** Introspección usada por el API Gateway para validar tokens entrantes. */
  introspect: {
    path: "/fintcart.auth.v1.AuthService/Introspect",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: IntrospectRequest) => Buffer.from(IntrospectRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => IntrospectRequest.decode(value),
    responseSerialize: (value: IntrospectResponse) => Buffer.from(IntrospectResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => IntrospectResponse.decode(value),
  },
  /** Paso de la Saga de anonimización (FR-030): revoca y anonimiza la credencial. */
  revokeAndAnonymizeCredential: {
    path: "/fintcart.auth.v1.AuthService/RevokeAndAnonymizeCredential",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserRef) => Buffer.from(UserRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserRef.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
  /**
   * Cambia la contraseña de una cuenta activa (FR-005). Exige la contraseña
   * ACTUAL: a diferencia del restablecimiento por enlace de correo (fuera del
   * alcance de este contrato — no tiene RPC propio todavía), este flujo lo invoca
   * un usuario YA AUTENTICADO desde su perfil, así que la prueba de identidad es
   * la contraseña vigente y no un token de un solo uso. Invalida las sesiones
   * abiertas (refresh tokens) y publica `auth.password_changed`.
   */
  changePassword: {
    path: "/fintcart.auth.v1.AuthService/ChangePassword",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ChangePasswordRequest) => Buffer.from(ChangePasswordRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ChangePasswordRequest.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
} as const;

export interface AuthServiceServer extends UntypedServiceImplementation {
  /**
   * Paso de la Saga de registro (research D-04): crea la credencial en estado
   * pending_verification. Idempotente por user_id.
   */
  createCredential: handleUnaryCall<CreateCredentialRequest, OpResult>;
  /**
   * Emite (o REEMITE) el token de verificación de correo.
   *
   * Lo invoca el paso de la saga de registro que produce el evento `user.registered`,
   * y el reenvío del correo cuando el enlace caduca (FR-002). Cada llamada SUSTITUYE
   * al token anterior: un reenvío tiene que invalidar el enlace previo, porque si no
   * un correo interceptado seguiría sirviendo indefinidamente.
   *
   * El valor en claro se devuelve UNA sola vez y no se puede volver a consultar: en
   * la base solo queda su hash. Quien pierda la respuesta tiene que reemitir.
   */
  issueVerificationToken: handleUnaryCall<UserRef, VerificationToken>;
  /** Activa la credencial tras verificación de correo (Saga de verificación). */
  activateCredential: handleUnaryCall<ActivateCredentialRequest, OpResult>;
  /** Valida correo+contraseña durante el login del Authorization Code flow. */
  validateCredentials: handleUnaryCall<ValidateCredentialsRequest, ValidateCredentialsResponse>;
  /** Emite un authorization_code (PKCE) tras autenticación exitosa. */
  issueAuthorizationCode: handleUnaryCall<IssueAuthCodeRequest, IssueAuthCodeResponse>;
  /** Intercambia authorization_code + code_verifier por tokens. */
  exchangeCode: handleUnaryCall<ExchangeCodeRequest, TokenResponse>;
  /** Rota un refresh token (rotación obligatoria, research D-05). */
  refreshToken: handleUnaryCall<RefreshTokenRequest, TokenResponse>;
  /** Revoca un token (logout con efecto inmediato, FR-004): añade jti a blacklist. */
  revoke: handleUnaryCall<RevokeRequest, OpResult>;
  /** Introspección usada por el API Gateway para validar tokens entrantes. */
  introspect: handleUnaryCall<IntrospectRequest, IntrospectResponse>;
  /** Paso de la Saga de anonimización (FR-030): revoca y anonimiza la credencial. */
  revokeAndAnonymizeCredential: handleUnaryCall<UserRef, OpResult>;
  /**
   * Cambia la contraseña de una cuenta activa (FR-005). Exige la contraseña
   * ACTUAL: a diferencia del restablecimiento por enlace de correo (fuera del
   * alcance de este contrato — no tiene RPC propio todavía), este flujo lo invoca
   * un usuario YA AUTENTICADO desde su perfil, así que la prueba de identidad es
   * la contraseña vigente y no un token de un solo uso. Invalida las sesiones
   * abiertas (refresh tokens) y publica `auth.password_changed`.
   */
  changePassword: handleUnaryCall<ChangePasswordRequest, OpResult>;
}

export interface AuthServiceClient extends Client {
  /**
   * Paso de la Saga de registro (research D-04): crea la credencial en estado
   * pending_verification. Idempotente por user_id.
   */
  createCredential(
    request: CreateCredentialRequest,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  createCredential(
    request: CreateCredentialRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  createCredential(
    request: CreateCredentialRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  /**
   * Emite (o REEMITE) el token de verificación de correo.
   *
   * Lo invoca el paso de la saga de registro que produce el evento `user.registered`,
   * y el reenvío del correo cuando el enlace caduca (FR-002). Cada llamada SUSTITUYE
   * al token anterior: un reenvío tiene que invalidar el enlace previo, porque si no
   * un correo interceptado seguiría sirviendo indefinidamente.
   *
   * El valor en claro se devuelve UNA sola vez y no se puede volver a consultar: en
   * la base solo queda su hash. Quien pierda la respuesta tiene que reemitir.
   */
  issueVerificationToken(
    request: UserRef,
    callback: (error: ServiceError | null, response: VerificationToken) => void,
  ): ClientUnaryCall;
  issueVerificationToken(
    request: UserRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VerificationToken) => void,
  ): ClientUnaryCall;
  issueVerificationToken(
    request: UserRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VerificationToken) => void,
  ): ClientUnaryCall;
  /** Activa la credencial tras verificación de correo (Saga de verificación). */
  activateCredential(
    request: ActivateCredentialRequest,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  activateCredential(
    request: ActivateCredentialRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  activateCredential(
    request: ActivateCredentialRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  /** Valida correo+contraseña durante el login del Authorization Code flow. */
  validateCredentials(
    request: ValidateCredentialsRequest,
    callback: (error: ServiceError | null, response: ValidateCredentialsResponse) => void,
  ): ClientUnaryCall;
  validateCredentials(
    request: ValidateCredentialsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ValidateCredentialsResponse) => void,
  ): ClientUnaryCall;
  validateCredentials(
    request: ValidateCredentialsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ValidateCredentialsResponse) => void,
  ): ClientUnaryCall;
  /** Emite un authorization_code (PKCE) tras autenticación exitosa. */
  issueAuthorizationCode(
    request: IssueAuthCodeRequest,
    callback: (error: ServiceError | null, response: IssueAuthCodeResponse) => void,
  ): ClientUnaryCall;
  issueAuthorizationCode(
    request: IssueAuthCodeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: IssueAuthCodeResponse) => void,
  ): ClientUnaryCall;
  issueAuthorizationCode(
    request: IssueAuthCodeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: IssueAuthCodeResponse) => void,
  ): ClientUnaryCall;
  /** Intercambia authorization_code + code_verifier por tokens. */
  exchangeCode(
    request: ExchangeCodeRequest,
    callback: (error: ServiceError | null, response: TokenResponse) => void,
  ): ClientUnaryCall;
  exchangeCode(
    request: ExchangeCodeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TokenResponse) => void,
  ): ClientUnaryCall;
  exchangeCode(
    request: ExchangeCodeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TokenResponse) => void,
  ): ClientUnaryCall;
  /** Rota un refresh token (rotación obligatoria, research D-05). */
  refreshToken(
    request: RefreshTokenRequest,
    callback: (error: ServiceError | null, response: TokenResponse) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: RefreshTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TokenResponse) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: RefreshTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TokenResponse) => void,
  ): ClientUnaryCall;
  /** Revoca un token (logout con efecto inmediato, FR-004): añade jti a blacklist. */
  revoke(request: RevokeRequest, callback: (error: ServiceError | null, response: OpResult) => void): ClientUnaryCall;
  revoke(
    request: RevokeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  revoke(
    request: RevokeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  /** Introspección usada por el API Gateway para validar tokens entrantes. */
  introspect(
    request: IntrospectRequest,
    callback: (error: ServiceError | null, response: IntrospectResponse) => void,
  ): ClientUnaryCall;
  introspect(
    request: IntrospectRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: IntrospectResponse) => void,
  ): ClientUnaryCall;
  introspect(
    request: IntrospectRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: IntrospectResponse) => void,
  ): ClientUnaryCall;
  /** Paso de la Saga de anonimización (FR-030): revoca y anonimiza la credencial. */
  revokeAndAnonymizeCredential(
    request: UserRef,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  revokeAndAnonymizeCredential(
    request: UserRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  revokeAndAnonymizeCredential(
    request: UserRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  /**
   * Cambia la contraseña de una cuenta activa (FR-005). Exige la contraseña
   * ACTUAL: a diferencia del restablecimiento por enlace de correo (fuera del
   * alcance de este contrato — no tiene RPC propio todavía), este flujo lo invoca
   * un usuario YA AUTENTICADO desde su perfil, así que la prueba de identidad es
   * la contraseña vigente y no un token de un solo uso. Invalida las sesiones
   * abiertas (refresh tokens) y publica `auth.password_changed`.
   */
  changePassword(
    request: ChangePasswordRequest,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  changePassword(
    request: ChangePasswordRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  changePassword(
    request: ChangePasswordRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
}

export const AuthServiceClient = makeGenericClientConstructor(
  AuthServiceService,
  "fintcart.auth.v1.AuthService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AuthServiceClient;
  service: typeof AuthServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
