// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: fintcart/users/v1/users.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { PageRequest, PageResponse } from '../../common/v1/common.js';

export const protobufPackage = 'fintcart.users.v1';

export interface UserRef {
  user_id: string;
}

export interface CreateProfileRequest {
  user_id: string;
  email: string;
  display_name: string;
}

export interface AuthContext {
  user_id: string;
  /** usuario_final | editor | coordinador_editorial */
  roles: string[];
  /** active | anonymized */
  account_status: string;
  email_verified: boolean;
}

export interface Profile {
  user_id: string;
  email: string;
  display_name: string;
  email_verified: boolean;
  account_status: string;
  preferences: { [key: string]: string };
  roles: string[];
}

export interface Profile_PreferencesEntry {
  key: string;
  value: string;
}

export interface UpdateProfileRequest {
  user_id: string;
  display_name: string;
  preferences: { [key: string]: string };
}

export interface UpdateProfileRequest_PreferencesEntry {
  key: string;
  value: string;
}

export interface ApplyQuizScoreRequest {
  user_id: string;
  quiz_id: string;
  /** [decimal] calificación del intento */
  score: string;
}

export interface ProgressView {
  user_id: string;
  /** Σ mejor puntaje por cuestionario distinto (FR-014) */
  points: number;
}

export interface RecordArticleViewRequest {
  user_id: string;
  article_id: string;
}

export interface InAppNotification {
  user_id: string;
  /** nuevo_articulo | recordatorio | hito_progreso | resultado_cuestionario */
  type: string;
  payload_json: string;
  /**
   * Clave de idempotencia de la OCURRENCIA que originó la notificación (UUID).
   * OBLIGATORIO.
   *
   * La entrega de la saga es at-least-once, así que una reentrega es normal y no
   * excepcional. Sin esta clave habría que deducir la identidad del CONTENIDO, y dos
   * notificaciones legítimamente idénticas —el mismo hito alcanzado dos veces—
   * colapsarían en una sola sin que nada lo delatara.
   *
   * Cuando quien llama es un paso de saga, el valor es el **saga_id**: es lo único
   * estable entre reintentos del paso, porque el `event_id` del outbox se genera de
   * nuevo cada vez que un paso devuelve sus eventos.
   *
   * La misma ocurrencia puede producir varias notificaciones (p. ej. resultado del
   * cuestionario e hito de progreso): la identidad de la entrada es el par
   * (`event_id`, `type`), no el `event_id` a solas.
   */
  event_id: string;
}

export interface ListInAppRequest {
  user_id: string;
  page?: PageRequest | undefined;
}

export interface ListInAppResponse {
  items: ListInAppResponse_Item[];
  page?: PageResponse | undefined;
}

export interface ListInAppResponse_Item {
  id: string;
  type: string;
  payload_json: string;
  /** unread | read */
  read_state: string;
  /** RFC-3339 */
  created_at: string;
}

export interface MarkReadRequest {
  user_id: string;
  notification_id: string;
}

export interface ActivityReport {
  user_id: string;
  points: number;
  articles_viewed: string;
  quizzes_attempted: string;
  simulations_run: string;
}

function createBaseUserRef(): UserRef {
  return { user_id: '' };
}

export const UserRef: MessageFns<UserRef> = {
  encode(message: UserRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRef {
    return { user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '' };
  },

  toJSON(message: UserRef): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRef>, I>>(base?: I): UserRef {
    return UserRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRef>, I>>(object: I): UserRef {
    const message = createBaseUserRef();
    message.user_id = object.user_id ?? '';
    return message;
  },
};

function createBaseCreateProfileRequest(): CreateProfileRequest {
  return { user_id: '', email: '', display_name: '' };
}

export const CreateProfileRequest: MessageFns<CreateProfileRequest> = {
  encode(message: CreateProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.email !== '') {
      writer.uint32(18).string(message.email);
    }
    if (message.display_name !== '') {
      writer.uint32(26).string(message.display_name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.display_name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProfileRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      email: isSet(object.email) ? globalThis.String(object.email) : '',
      display_name: isSet(object.display_name) ? globalThis.String(object.display_name) : '',
    };
  },

  toJSON(message: CreateProfileRequest): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.email !== '') {
      obj.email = message.email;
    }
    if (message.display_name !== '') {
      obj.display_name = message.display_name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateProfileRequest>, I>>(base?: I): CreateProfileRequest {
    return CreateProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateProfileRequest>, I>>(
    object: I,
  ): CreateProfileRequest {
    const message = createBaseCreateProfileRequest();
    message.user_id = object.user_id ?? '';
    message.email = object.email ?? '';
    message.display_name = object.display_name ?? '';
    return message;
  },
};

function createBaseAuthContext(): AuthContext {
  return { user_id: '', roles: [], account_status: '', email_verified: false };
}

export const AuthContext: MessageFns<AuthContext> = {
  encode(message: AuthContext, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    for (const v of message.roles) {
      writer.uint32(18).string(v!);
    }
    if (message.account_status !== '') {
      writer.uint32(26).string(message.account_status);
    }
    if (message.email_verified !== false) {
      writer.uint32(32).bool(message.email_verified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthContext {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.roles.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.account_status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.email_verified = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthContext {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      roles: globalThis.Array.isArray(object?.roles)
        ? object.roles.map((e: any) => globalThis.String(e))
        : [],
      account_status: isSet(object.account_status) ? globalThis.String(object.account_status) : '',
      email_verified: isSet(object.email_verified)
        ? globalThis.Boolean(object.email_verified)
        : false,
    };
  },

  toJSON(message: AuthContext): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.roles?.length) {
      obj.roles = message.roles;
    }
    if (message.account_status !== '') {
      obj.account_status = message.account_status;
    }
    if (message.email_verified !== false) {
      obj.email_verified = message.email_verified;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthContext>, I>>(base?: I): AuthContext {
    return AuthContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthContext>, I>>(object: I): AuthContext {
    const message = createBaseAuthContext();
    message.user_id = object.user_id ?? '';
    message.roles = object.roles?.map((e) => e) || [];
    message.account_status = object.account_status ?? '';
    message.email_verified = object.email_verified ?? false;
    return message;
  },
};

function createBaseProfile(): Profile {
  return {
    user_id: '',
    email: '',
    display_name: '',
    email_verified: false,
    account_status: '',
    preferences: {},
    roles: [],
  };
}

export const Profile: MessageFns<Profile> = {
  encode(message: Profile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.email !== '') {
      writer.uint32(18).string(message.email);
    }
    if (message.display_name !== '') {
      writer.uint32(26).string(message.display_name);
    }
    if (message.email_verified !== false) {
      writer.uint32(32).bool(message.email_verified);
    }
    if (message.account_status !== '') {
      writer.uint32(42).string(message.account_status);
    }
    Object.entries(message.preferences).forEach(([key, value]) => {
      Profile_PreferencesEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    for (const v of message.roles) {
      writer.uint32(58).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Profile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.display_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.email_verified = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.account_status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = Profile_PreferencesEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.preferences[entry6.key] = entry6.value;
          }
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.roles.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Profile {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      email: isSet(object.email) ? globalThis.String(object.email) : '',
      display_name: isSet(object.display_name) ? globalThis.String(object.display_name) : '',
      email_verified: isSet(object.email_verified)
        ? globalThis.Boolean(object.email_verified)
        : false,
      account_status: isSet(object.account_status) ? globalThis.String(object.account_status) : '',
      preferences: isObject(object.preferences)
        ? Object.entries(object.preferences).reduce<{ [key: string]: string }>(
            (acc, [key, value]) => {
              acc[key] = String(value);
              return acc;
            },
            {},
          )
        : {},
      roles: globalThis.Array.isArray(object?.roles)
        ? object.roles.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Profile): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.email !== '') {
      obj.email = message.email;
    }
    if (message.display_name !== '') {
      obj.display_name = message.display_name;
    }
    if (message.email_verified !== false) {
      obj.email_verified = message.email_verified;
    }
    if (message.account_status !== '') {
      obj.account_status = message.account_status;
    }
    if (message.preferences) {
      const entries = Object.entries(message.preferences);
      if (entries.length > 0) {
        obj.preferences = {};
        entries.forEach(([k, v]) => {
          obj.preferences[k] = v;
        });
      }
    }
    if (message.roles?.length) {
      obj.roles = message.roles;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Profile>, I>>(base?: I): Profile {
    return Profile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Profile>, I>>(object: I): Profile {
    const message = createBaseProfile();
    message.user_id = object.user_id ?? '';
    message.email = object.email ?? '';
    message.display_name = object.display_name ?? '';
    message.email_verified = object.email_verified ?? false;
    message.account_status = object.account_status ?? '';
    message.preferences = Object.entries(object.preferences ?? {}).reduce<{
      [key: string]: string;
    }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.roles = object.roles?.map((e) => e) || [];
    return message;
  },
};

function createBaseProfile_PreferencesEntry(): Profile_PreferencesEntry {
  return { key: '', value: '' };
}

export const Profile_PreferencesEntry: MessageFns<Profile_PreferencesEntry> = {
  encode(
    message: Profile_PreferencesEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== '') {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== '') {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Profile_PreferencesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfile_PreferencesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Profile_PreferencesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? globalThis.String(object.value) : '',
    };
  },

  toJSON(message: Profile_PreferencesEntry): unknown {
    const obj: any = {};
    if (message.key !== '') {
      obj.key = message.key;
    }
    if (message.value !== '') {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Profile_PreferencesEntry>, I>>(
    base?: I,
  ): Profile_PreferencesEntry {
    return Profile_PreferencesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Profile_PreferencesEntry>, I>>(
    object: I,
  ): Profile_PreferencesEntry {
    const message = createBaseProfile_PreferencesEntry();
    message.key = object.key ?? '';
    message.value = object.value ?? '';
    return message;
  },
};

function createBaseUpdateProfileRequest(): UpdateProfileRequest {
  return { user_id: '', display_name: '', preferences: {} };
}

export const UpdateProfileRequest: MessageFns<UpdateProfileRequest> = {
  encode(message: UpdateProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.display_name !== '') {
      writer.uint32(18).string(message.display_name);
    }
    Object.entries(message.preferences).forEach(([key, value]) => {
      UpdateProfileRequest_PreferencesEntry.encode(
        { key: key as any, value },
        writer.uint32(26).fork(),
      ).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.display_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = UpdateProfileRequest_PreferencesEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.preferences[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateProfileRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      display_name: isSet(object.display_name) ? globalThis.String(object.display_name) : '',
      preferences: isObject(object.preferences)
        ? Object.entries(object.preferences).reduce<{ [key: string]: string }>(
            (acc, [key, value]) => {
              acc[key] = String(value);
              return acc;
            },
            {},
          )
        : {},
    };
  },

  toJSON(message: UpdateProfileRequest): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.display_name !== '') {
      obj.display_name = message.display_name;
    }
    if (message.preferences) {
      const entries = Object.entries(message.preferences);
      if (entries.length > 0) {
        obj.preferences = {};
        entries.forEach(([k, v]) => {
          obj.preferences[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateProfileRequest>, I>>(base?: I): UpdateProfileRequest {
    return UpdateProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateProfileRequest>, I>>(
    object: I,
  ): UpdateProfileRequest {
    const message = createBaseUpdateProfileRequest();
    message.user_id = object.user_id ?? '';
    message.display_name = object.display_name ?? '';
    message.preferences = Object.entries(object.preferences ?? {}).reduce<{
      [key: string]: string;
    }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseUpdateProfileRequest_PreferencesEntry(): UpdateProfileRequest_PreferencesEntry {
  return { key: '', value: '' };
}

export const UpdateProfileRequest_PreferencesEntry: MessageFns<UpdateProfileRequest_PreferencesEntry> =
  {
    encode(
      message: UpdateProfileRequest_PreferencesEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.key !== '') {
        writer.uint32(10).string(message.key);
      }
      if (message.value !== '') {
        writer.uint32(18).string(message.value);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): UpdateProfileRequest_PreferencesEntry {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      let end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseUpdateProfileRequest_PreferencesEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): UpdateProfileRequest_PreferencesEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : '',
        value: isSet(object.value) ? globalThis.String(object.value) : '',
      };
    },

    toJSON(message: UpdateProfileRequest_PreferencesEntry): unknown {
      const obj: any = {};
      if (message.key !== '') {
        obj.key = message.key;
      }
      if (message.value !== '') {
        obj.value = message.value;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<UpdateProfileRequest_PreferencesEntry>, I>>(
      base?: I,
    ): UpdateProfileRequest_PreferencesEntry {
      return UpdateProfileRequest_PreferencesEntry.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<UpdateProfileRequest_PreferencesEntry>, I>>(
      object: I,
    ): UpdateProfileRequest_PreferencesEntry {
      const message = createBaseUpdateProfileRequest_PreferencesEntry();
      message.key = object.key ?? '';
      message.value = object.value ?? '';
      return message;
    },
  };

function createBaseApplyQuizScoreRequest(): ApplyQuizScoreRequest {
  return { user_id: '', quiz_id: '', score: '' };
}

export const ApplyQuizScoreRequest: MessageFns<ApplyQuizScoreRequest> = {
  encode(message: ApplyQuizScoreRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.quiz_id !== '') {
      writer.uint32(18).string(message.quiz_id);
    }
    if (message.score !== '') {
      writer.uint32(26).string(message.score);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApplyQuizScoreRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApplyQuizScoreRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.quiz_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.score = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApplyQuizScoreRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      quiz_id: isSet(object.quiz_id) ? globalThis.String(object.quiz_id) : '',
      score: isSet(object.score) ? globalThis.String(object.score) : '',
    };
  },

  toJSON(message: ApplyQuizScoreRequest): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.quiz_id !== '') {
      obj.quiz_id = message.quiz_id;
    }
    if (message.score !== '') {
      obj.score = message.score;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApplyQuizScoreRequest>, I>>(base?: I): ApplyQuizScoreRequest {
    return ApplyQuizScoreRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApplyQuizScoreRequest>, I>>(
    object: I,
  ): ApplyQuizScoreRequest {
    const message = createBaseApplyQuizScoreRequest();
    message.user_id = object.user_id ?? '';
    message.quiz_id = object.quiz_id ?? '';
    message.score = object.score ?? '';
    return message;
  },
};

function createBaseProgressView(): ProgressView {
  return { user_id: '', points: 0 };
}

export const ProgressView: MessageFns<ProgressView> = {
  encode(message: ProgressView, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.points !== 0) {
      writer.uint32(16).int32(message.points);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProgressView {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProgressView();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.points = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProgressView {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      points: isSet(object.points) ? globalThis.Number(object.points) : 0,
    };
  },

  toJSON(message: ProgressView): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.points !== 0) {
      obj.points = Math.round(message.points);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProgressView>, I>>(base?: I): ProgressView {
    return ProgressView.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProgressView>, I>>(object: I): ProgressView {
    const message = createBaseProgressView();
    message.user_id = object.user_id ?? '';
    message.points = object.points ?? 0;
    return message;
  },
};

function createBaseRecordArticleViewRequest(): RecordArticleViewRequest {
  return { user_id: '', article_id: '' };
}

export const RecordArticleViewRequest: MessageFns<RecordArticleViewRequest> = {
  encode(
    message: RecordArticleViewRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.article_id !== '') {
      writer.uint32(18).string(message.article_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordArticleViewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordArticleViewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.article_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordArticleViewRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      article_id: isSet(object.article_id) ? globalThis.String(object.article_id) : '',
    };
  },

  toJSON(message: RecordArticleViewRequest): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.article_id !== '') {
      obj.article_id = message.article_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordArticleViewRequest>, I>>(
    base?: I,
  ): RecordArticleViewRequest {
    return RecordArticleViewRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordArticleViewRequest>, I>>(
    object: I,
  ): RecordArticleViewRequest {
    const message = createBaseRecordArticleViewRequest();
    message.user_id = object.user_id ?? '';
    message.article_id = object.article_id ?? '';
    return message;
  },
};

function createBaseInAppNotification(): InAppNotification {
  return { user_id: '', type: '', payload_json: '', event_id: '' };
}

export const InAppNotification: MessageFns<InAppNotification> = {
  encode(message: InAppNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.type !== '') {
      writer.uint32(18).string(message.type);
    }
    if (message.payload_json !== '') {
      writer.uint32(26).string(message.payload_json);
    }
    if (message.event_id !== '') {
      writer.uint32(34).string(message.event_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InAppNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInAppNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload_json = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.event_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InAppNotification {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      type: isSet(object.type) ? globalThis.String(object.type) : '',
      payload_json: isSet(object.payload_json) ? globalThis.String(object.payload_json) : '',
      event_id: isSet(object.event_id) ? globalThis.String(object.event_id) : '',
    };
  },

  toJSON(message: InAppNotification): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.type !== '') {
      obj.type = message.type;
    }
    if (message.payload_json !== '') {
      obj.payload_json = message.payload_json;
    }
    if (message.event_id !== '') {
      obj.event_id = message.event_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InAppNotification>, I>>(base?: I): InAppNotification {
    return InAppNotification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InAppNotification>, I>>(object: I): InAppNotification {
    const message = createBaseInAppNotification();
    message.user_id = object.user_id ?? '';
    message.type = object.type ?? '';
    message.payload_json = object.payload_json ?? '';
    message.event_id = object.event_id ?? '';
    return message;
  },
};

function createBaseListInAppRequest(): ListInAppRequest {
  return { user_id: '', page: undefined };
}

export const ListInAppRequest: MessageFns<ListInAppRequest> = {
  encode(message: ListInAppRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.page !== undefined) {
      PageRequest.encode(message.page, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInAppRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInAppRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.page = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListInAppRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      page: isSet(object.page) ? PageRequest.fromJSON(object.page) : undefined,
    };
  },

  toJSON(message: ListInAppRequest): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.page !== undefined) {
      obj.page = PageRequest.toJSON(message.page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListInAppRequest>, I>>(base?: I): ListInAppRequest {
    return ListInAppRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListInAppRequest>, I>>(object: I): ListInAppRequest {
    const message = createBaseListInAppRequest();
    message.user_id = object.user_id ?? '';
    message.page =
      object.page !== undefined && object.page !== null
        ? PageRequest.fromPartial(object.page)
        : undefined;
    return message;
  },
};

function createBaseListInAppResponse(): ListInAppResponse {
  return { items: [], page: undefined };
}

export const ListInAppResponse: MessageFns<ListInAppResponse> = {
  encode(message: ListInAppResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      ListInAppResponse_Item.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.page !== undefined) {
      PageResponse.encode(message.page, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInAppResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInAppResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(ListInAppResponse_Item.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.page = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListInAppResponse {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => ListInAppResponse_Item.fromJSON(e))
        : [],
      page: isSet(object.page) ? PageResponse.fromJSON(object.page) : undefined,
    };
  },

  toJSON(message: ListInAppResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => ListInAppResponse_Item.toJSON(e));
    }
    if (message.page !== undefined) {
      obj.page = PageResponse.toJSON(message.page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListInAppResponse>, I>>(base?: I): ListInAppResponse {
    return ListInAppResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListInAppResponse>, I>>(object: I): ListInAppResponse {
    const message = createBaseListInAppResponse();
    message.items = object.items?.map((e) => ListInAppResponse_Item.fromPartial(e)) || [];
    message.page =
      object.page !== undefined && object.page !== null
        ? PageResponse.fromPartial(object.page)
        : undefined;
    return message;
  },
};

function createBaseListInAppResponse_Item(): ListInAppResponse_Item {
  return { id: '', type: '', payload_json: '', read_state: '', created_at: '' };
}

export const ListInAppResponse_Item: MessageFns<ListInAppResponse_Item> = {
  encode(message: ListInAppResponse_Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== '') {
      writer.uint32(18).string(message.type);
    }
    if (message.payload_json !== '') {
      writer.uint32(26).string(message.payload_json);
    }
    if (message.read_state !== '') {
      writer.uint32(34).string(message.read_state);
    }
    if (message.created_at !== '') {
      writer.uint32(42).string(message.created_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInAppResponse_Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInAppResponse_Item();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload_json = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.read_state = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListInAppResponse_Item {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      type: isSet(object.type) ? globalThis.String(object.type) : '',
      payload_json: isSet(object.payload_json) ? globalThis.String(object.payload_json) : '',
      read_state: isSet(object.read_state) ? globalThis.String(object.read_state) : '',
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : '',
    };
  },

  toJSON(message: ListInAppResponse_Item): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.type !== '') {
      obj.type = message.type;
    }
    if (message.payload_json !== '') {
      obj.payload_json = message.payload_json;
    }
    if (message.read_state !== '') {
      obj.read_state = message.read_state;
    }
    if (message.created_at !== '') {
      obj.created_at = message.created_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListInAppResponse_Item>, I>>(
    base?: I,
  ): ListInAppResponse_Item {
    return ListInAppResponse_Item.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListInAppResponse_Item>, I>>(
    object: I,
  ): ListInAppResponse_Item {
    const message = createBaseListInAppResponse_Item();
    message.id = object.id ?? '';
    message.type = object.type ?? '';
    message.payload_json = object.payload_json ?? '';
    message.read_state = object.read_state ?? '';
    message.created_at = object.created_at ?? '';
    return message;
  },
};

function createBaseMarkReadRequest(): MarkReadRequest {
  return { user_id: '', notification_id: '' };
}

export const MarkReadRequest: MessageFns<MarkReadRequest> = {
  encode(message: MarkReadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.notification_id !== '') {
      writer.uint32(18).string(message.notification_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarkReadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarkReadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notification_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarkReadRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      notification_id: isSet(object.notification_id)
        ? globalThis.String(object.notification_id)
        : '',
    };
  },

  toJSON(message: MarkReadRequest): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.notification_id !== '') {
      obj.notification_id = message.notification_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarkReadRequest>, I>>(base?: I): MarkReadRequest {
    return MarkReadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarkReadRequest>, I>>(object: I): MarkReadRequest {
    const message = createBaseMarkReadRequest();
    message.user_id = object.user_id ?? '';
    message.notification_id = object.notification_id ?? '';
    return message;
  },
};

function createBaseActivityReport(): ActivityReport {
  return {
    user_id: '',
    points: 0,
    articles_viewed: '0',
    quizzes_attempted: '0',
    simulations_run: '0',
  };
}

export const ActivityReport: MessageFns<ActivityReport> = {
  encode(message: ActivityReport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== '') {
      writer.uint32(10).string(message.user_id);
    }
    if (message.points !== 0) {
      writer.uint32(16).int32(message.points);
    }
    if (message.articles_viewed !== '0') {
      writer.uint32(24).int64(message.articles_viewed);
    }
    if (message.quizzes_attempted !== '0') {
      writer.uint32(32).int64(message.quizzes_attempted);
    }
    if (message.simulations_run !== '0') {
      writer.uint32(40).int64(message.simulations_run);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActivityReport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActivityReport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.points = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.articles_viewed = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.quizzes_attempted = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.simulations_run = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActivityReport {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : '',
      points: isSet(object.points) ? globalThis.Number(object.points) : 0,
      articles_viewed: isSet(object.articles_viewed)
        ? globalThis.String(object.articles_viewed)
        : '0',
      quizzes_attempted: isSet(object.quizzes_attempted)
        ? globalThis.String(object.quizzes_attempted)
        : '0',
      simulations_run: isSet(object.simulations_run)
        ? globalThis.String(object.simulations_run)
        : '0',
    };
  },

  toJSON(message: ActivityReport): unknown {
    const obj: any = {};
    if (message.user_id !== '') {
      obj.user_id = message.user_id;
    }
    if (message.points !== 0) {
      obj.points = Math.round(message.points);
    }
    if (message.articles_viewed !== '0') {
      obj.articles_viewed = message.articles_viewed;
    }
    if (message.quizzes_attempted !== '0') {
      obj.quizzes_attempted = message.quizzes_attempted;
    }
    if (message.simulations_run !== '0') {
      obj.simulations_run = message.simulations_run;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActivityReport>, I>>(base?: I): ActivityReport {
    return ActivityReport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActivityReport>, I>>(object: I): ActivityReport {
    const message = createBaseActivityReport();
    message.user_id = object.user_id ?? '';
    message.points = object.points ?? 0;
    message.articles_viewed = object.articles_viewed ?? '0';
    message.quizzes_attempted = object.quizzes_attempted ?? '0';
    message.simulations_run = object.simulations_run ?? '0';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === 'object' && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
