// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: fintcart/learning/v1/learning.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { OpResult, PageRequest, PageResponse } from "../../common/v1/common";

export const protobufPackage = "fintcart.learning.v1";

export interface UserRef {
  user_id: string;
}

export interface ArticleRef {
  article_id: string;
}

export interface VersionRef {
  version_id: string;
  actor_id: string;
}

export interface QuizRef {
  quiz_id: string;
}

export interface ArticleVersion {
  version_id: string;
  article_id: string;
  version_no: number;
  /** borrador | en_revision | publicado | archivado */
  state: string;
  created_by: string;
  /** vacío hasta aprobación; DEBE diferir de created_by */
  approved_by: string;
}

export interface CreateDraftRequest {
  title: string;
  category: string;
  body: string;
  /** rol editor (FR-006) */
  editor_id: string;
}

export interface UpdateDraftRequest {
  version_id: string;
  body: string;
  editor_id: string;
}

export interface ApprovePublishRequest {
  version_id: string;
  /** rol coordinador_editorial; validar ≠ created_by (FR-008) */
  coordinator_id: string;
}

export interface ListPublishedRequest {
  category: string;
  page?: PageRequest | undefined;
}

export interface ListPublishedResponse {
  items: Article[];
  page?: PageResponse | undefined;
}

export interface Article {
  article_id: string;
  title: string;
  category: string;
  body: string;
  current_version_no: number;
  quiz_ids: string[];
}

export interface Quiz {
  quiz_id: string;
  article_id: string;
  title: string;
  /** [decimal] */
  pass_threshold: string;
  questions: Question[];
}

export interface Question {
  question_id: string;
  prompt: string;
  options: Option[];
  /** [decimal] */
  weight: string;
}

/**
 * Option es una alternativa de respuesta.
 *
 * Lleva CLAVE y texto, no solo el texto. `GradeRequest.answers` mapea
 * `question_id -> option_key`, así que un cliente que recibiera únicamente los
 * enunciados no tendría con qué responder: el cuestionario sería literalmente
 * incontestable. Es el mismo par que guarda la columna `questions.options`
 * (JSONB `{clave: enunciado}`) del esquema de Aprendizaje.
 */
export interface Option {
  key: string;
  text: string;
}

export interface GradeRequest {
  user_id: string;
  quiz_id: string;
  /** question_id -> option_key */
  answers: { [key: string]: string };
}

export interface GradeRequest_AnswersEntry {
  key: string;
  value: string;
}

export interface GradeResponse {
  attempt_id: string;
  attempt_no: number;
  /** [decimal] */
  score: string;
  passed: boolean;
}

export interface ListAttemptsRequest {
  user_id: string;
  quiz_id: string;
  page?: PageRequest | undefined;
}

export interface ListAttemptsResponse {
  items: ListAttemptsResponse_Attempt[];
  page?: PageResponse | undefined;
}

export interface ListAttemptsResponse_Attempt {
  attempt_id: string;
  attempt_no: number;
  /** [decimal] */
  score: string;
  created_at: string;
}

function createBaseUserRef(): UserRef {
  return { user_id: "" };
}

export const UserRef: MessageFns<UserRef> = {
  encode(message: UserRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRef {
    return { user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "" };
  },

  toJSON(message: UserRef): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRef>, I>>(base?: I): UserRef {
    return UserRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRef>, I>>(object: I): UserRef {
    const message = createBaseUserRef();
    message.user_id = object.user_id ?? "";
    return message;
  },
};

function createBaseArticleRef(): ArticleRef {
  return { article_id: "" };
}

export const ArticleRef: MessageFns<ArticleRef> = {
  encode(message: ArticleRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.article_id !== "") {
      writer.uint32(10).string(message.article_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArticleRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArticleRef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.article_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArticleRef {
    return { article_id: isSet(object.article_id) ? globalThis.String(object.article_id) : "" };
  },

  toJSON(message: ArticleRef): unknown {
    const obj: any = {};
    if (message.article_id !== "") {
      obj.article_id = message.article_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArticleRef>, I>>(base?: I): ArticleRef {
    return ArticleRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArticleRef>, I>>(object: I): ArticleRef {
    const message = createBaseArticleRef();
    message.article_id = object.article_id ?? "";
    return message;
  },
};

function createBaseVersionRef(): VersionRef {
  return { version_id: "", actor_id: "" };
}

export const VersionRef: MessageFns<VersionRef> = {
  encode(message: VersionRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version_id !== "") {
      writer.uint32(10).string(message.version_id);
    }
    if (message.actor_id !== "") {
      writer.uint32(18).string(message.actor_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VersionRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVersionRef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.actor_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VersionRef {
    return {
      version_id: isSet(object.version_id) ? globalThis.String(object.version_id) : "",
      actor_id: isSet(object.actor_id) ? globalThis.String(object.actor_id) : "",
    };
  },

  toJSON(message: VersionRef): unknown {
    const obj: any = {};
    if (message.version_id !== "") {
      obj.version_id = message.version_id;
    }
    if (message.actor_id !== "") {
      obj.actor_id = message.actor_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VersionRef>, I>>(base?: I): VersionRef {
    return VersionRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VersionRef>, I>>(object: I): VersionRef {
    const message = createBaseVersionRef();
    message.version_id = object.version_id ?? "";
    message.actor_id = object.actor_id ?? "";
    return message;
  },
};

function createBaseQuizRef(): QuizRef {
  return { quiz_id: "" };
}

export const QuizRef: MessageFns<QuizRef> = {
  encode(message: QuizRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.quiz_id !== "") {
      writer.uint32(10).string(message.quiz_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuizRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuizRef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.quiz_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuizRef {
    return { quiz_id: isSet(object.quiz_id) ? globalThis.String(object.quiz_id) : "" };
  },

  toJSON(message: QuizRef): unknown {
    const obj: any = {};
    if (message.quiz_id !== "") {
      obj.quiz_id = message.quiz_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuizRef>, I>>(base?: I): QuizRef {
    return QuizRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuizRef>, I>>(object: I): QuizRef {
    const message = createBaseQuizRef();
    message.quiz_id = object.quiz_id ?? "";
    return message;
  },
};

function createBaseArticleVersion(): ArticleVersion {
  return { version_id: "", article_id: "", version_no: 0, state: "", created_by: "", approved_by: "" };
}

export const ArticleVersion: MessageFns<ArticleVersion> = {
  encode(message: ArticleVersion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version_id !== "") {
      writer.uint32(10).string(message.version_id);
    }
    if (message.article_id !== "") {
      writer.uint32(18).string(message.article_id);
    }
    if (message.version_no !== 0) {
      writer.uint32(24).int32(message.version_no);
    }
    if (message.state !== "") {
      writer.uint32(34).string(message.state);
    }
    if (message.created_by !== "") {
      writer.uint32(42).string(message.created_by);
    }
    if (message.approved_by !== "") {
      writer.uint32(50).string(message.approved_by);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArticleVersion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArticleVersion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.article_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version_no = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.created_by = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.approved_by = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArticleVersion {
    return {
      version_id: isSet(object.version_id) ? globalThis.String(object.version_id) : "",
      article_id: isSet(object.article_id) ? globalThis.String(object.article_id) : "",
      version_no: isSet(object.version_no) ? globalThis.Number(object.version_no) : 0,
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      created_by: isSet(object.created_by) ? globalThis.String(object.created_by) : "",
      approved_by: isSet(object.approved_by) ? globalThis.String(object.approved_by) : "",
    };
  },

  toJSON(message: ArticleVersion): unknown {
    const obj: any = {};
    if (message.version_id !== "") {
      obj.version_id = message.version_id;
    }
    if (message.article_id !== "") {
      obj.article_id = message.article_id;
    }
    if (message.version_no !== 0) {
      obj.version_no = Math.round(message.version_no);
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.created_by !== "") {
      obj.created_by = message.created_by;
    }
    if (message.approved_by !== "") {
      obj.approved_by = message.approved_by;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArticleVersion>, I>>(base?: I): ArticleVersion {
    return ArticleVersion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArticleVersion>, I>>(object: I): ArticleVersion {
    const message = createBaseArticleVersion();
    message.version_id = object.version_id ?? "";
    message.article_id = object.article_id ?? "";
    message.version_no = object.version_no ?? 0;
    message.state = object.state ?? "";
    message.created_by = object.created_by ?? "";
    message.approved_by = object.approved_by ?? "";
    return message;
  },
};

function createBaseCreateDraftRequest(): CreateDraftRequest {
  return { title: "", category: "", body: "", editor_id: "" };
}

export const CreateDraftRequest: MessageFns<CreateDraftRequest> = {
  encode(message: CreateDraftRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.category !== "") {
      writer.uint32(18).string(message.category);
    }
    if (message.body !== "") {
      writer.uint32(26).string(message.body);
    }
    if (message.editor_id !== "") {
      writer.uint32(34).string(message.editor_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateDraftRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDraftRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.editor_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateDraftRequest {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      editor_id: isSet(object.editor_id) ? globalThis.String(object.editor_id) : "",
    };
  },

  toJSON(message: CreateDraftRequest): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.editor_id !== "") {
      obj.editor_id = message.editor_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateDraftRequest>, I>>(base?: I): CreateDraftRequest {
    return CreateDraftRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateDraftRequest>, I>>(object: I): CreateDraftRequest {
    const message = createBaseCreateDraftRequest();
    message.title = object.title ?? "";
    message.category = object.category ?? "";
    message.body = object.body ?? "";
    message.editor_id = object.editor_id ?? "";
    return message;
  },
};

function createBaseUpdateDraftRequest(): UpdateDraftRequest {
  return { version_id: "", body: "", editor_id: "" };
}

export const UpdateDraftRequest: MessageFns<UpdateDraftRequest> = {
  encode(message: UpdateDraftRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version_id !== "") {
      writer.uint32(10).string(message.version_id);
    }
    if (message.body !== "") {
      writer.uint32(18).string(message.body);
    }
    if (message.editor_id !== "") {
      writer.uint32(26).string(message.editor_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateDraftRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateDraftRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.editor_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateDraftRequest {
    return {
      version_id: isSet(object.version_id) ? globalThis.String(object.version_id) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      editor_id: isSet(object.editor_id) ? globalThis.String(object.editor_id) : "",
    };
  },

  toJSON(message: UpdateDraftRequest): unknown {
    const obj: any = {};
    if (message.version_id !== "") {
      obj.version_id = message.version_id;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.editor_id !== "") {
      obj.editor_id = message.editor_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateDraftRequest>, I>>(base?: I): UpdateDraftRequest {
    return UpdateDraftRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateDraftRequest>, I>>(object: I): UpdateDraftRequest {
    const message = createBaseUpdateDraftRequest();
    message.version_id = object.version_id ?? "";
    message.body = object.body ?? "";
    message.editor_id = object.editor_id ?? "";
    return message;
  },
};

function createBaseApprovePublishRequest(): ApprovePublishRequest {
  return { version_id: "", coordinator_id: "" };
}

export const ApprovePublishRequest: MessageFns<ApprovePublishRequest> = {
  encode(message: ApprovePublishRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version_id !== "") {
      writer.uint32(10).string(message.version_id);
    }
    if (message.coordinator_id !== "") {
      writer.uint32(18).string(message.coordinator_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApprovePublishRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApprovePublishRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.coordinator_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApprovePublishRequest {
    return {
      version_id: isSet(object.version_id) ? globalThis.String(object.version_id) : "",
      coordinator_id: isSet(object.coordinator_id) ? globalThis.String(object.coordinator_id) : "",
    };
  },

  toJSON(message: ApprovePublishRequest): unknown {
    const obj: any = {};
    if (message.version_id !== "") {
      obj.version_id = message.version_id;
    }
    if (message.coordinator_id !== "") {
      obj.coordinator_id = message.coordinator_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApprovePublishRequest>, I>>(base?: I): ApprovePublishRequest {
    return ApprovePublishRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApprovePublishRequest>, I>>(object: I): ApprovePublishRequest {
    const message = createBaseApprovePublishRequest();
    message.version_id = object.version_id ?? "";
    message.coordinator_id = object.coordinator_id ?? "";
    return message;
  },
};

function createBaseListPublishedRequest(): ListPublishedRequest {
  return { category: "", page: undefined };
}

export const ListPublishedRequest: MessageFns<ListPublishedRequest> = {
  encode(message: ListPublishedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.category !== "") {
      writer.uint32(10).string(message.category);
    }
    if (message.page !== undefined) {
      PageRequest.encode(message.page, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPublishedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPublishedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.page = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPublishedRequest {
    return {
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      page: isSet(object.page) ? PageRequest.fromJSON(object.page) : undefined,
    };
  },

  toJSON(message: ListPublishedRequest): unknown {
    const obj: any = {};
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.page !== undefined) {
      obj.page = PageRequest.toJSON(message.page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPublishedRequest>, I>>(base?: I): ListPublishedRequest {
    return ListPublishedRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPublishedRequest>, I>>(object: I): ListPublishedRequest {
    const message = createBaseListPublishedRequest();
    message.category = object.category ?? "";
    message.page = (object.page !== undefined && object.page !== null)
      ? PageRequest.fromPartial(object.page)
      : undefined;
    return message;
  },
};

function createBaseListPublishedResponse(): ListPublishedResponse {
  return { items: [], page: undefined };
}

export const ListPublishedResponse: MessageFns<ListPublishedResponse> = {
  encode(message: ListPublishedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      Article.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.page !== undefined) {
      PageResponse.encode(message.page, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPublishedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPublishedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(Article.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.page = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPublishedResponse {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => Article.fromJSON(e)) : [],
      page: isSet(object.page) ? PageResponse.fromJSON(object.page) : undefined,
    };
  },

  toJSON(message: ListPublishedResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => Article.toJSON(e));
    }
    if (message.page !== undefined) {
      obj.page = PageResponse.toJSON(message.page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPublishedResponse>, I>>(base?: I): ListPublishedResponse {
    return ListPublishedResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPublishedResponse>, I>>(object: I): ListPublishedResponse {
    const message = createBaseListPublishedResponse();
    message.items = object.items?.map((e) => Article.fromPartial(e)) || [];
    message.page = (object.page !== undefined && object.page !== null)
      ? PageResponse.fromPartial(object.page)
      : undefined;
    return message;
  },
};

function createBaseArticle(): Article {
  return { article_id: "", title: "", category: "", body: "", current_version_no: 0, quiz_ids: [] };
}

export const Article: MessageFns<Article> = {
  encode(message: Article, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.article_id !== "") {
      writer.uint32(10).string(message.article_id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.category !== "") {
      writer.uint32(26).string(message.category);
    }
    if (message.body !== "") {
      writer.uint32(34).string(message.body);
    }
    if (message.current_version_no !== 0) {
      writer.uint32(40).int32(message.current_version_no);
    }
    for (const v of message.quiz_ids) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Article {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArticle();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.article_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.current_version_no = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.quiz_ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Article {
    return {
      article_id: isSet(object.article_id) ? globalThis.String(object.article_id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      current_version_no: isSet(object.current_version_no) ? globalThis.Number(object.current_version_no) : 0,
      quiz_ids: globalThis.Array.isArray(object?.quiz_ids) ? object.quiz_ids.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: Article): unknown {
    const obj: any = {};
    if (message.article_id !== "") {
      obj.article_id = message.article_id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.current_version_no !== 0) {
      obj.current_version_no = Math.round(message.current_version_no);
    }
    if (message.quiz_ids?.length) {
      obj.quiz_ids = message.quiz_ids;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Article>, I>>(base?: I): Article {
    return Article.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Article>, I>>(object: I): Article {
    const message = createBaseArticle();
    message.article_id = object.article_id ?? "";
    message.title = object.title ?? "";
    message.category = object.category ?? "";
    message.body = object.body ?? "";
    message.current_version_no = object.current_version_no ?? 0;
    message.quiz_ids = object.quiz_ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseQuiz(): Quiz {
  return { quiz_id: "", article_id: "", title: "", pass_threshold: "", questions: [] };
}

export const Quiz: MessageFns<Quiz> = {
  encode(message: Quiz, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.quiz_id !== "") {
      writer.uint32(10).string(message.quiz_id);
    }
    if (message.article_id !== "") {
      writer.uint32(18).string(message.article_id);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.pass_threshold !== "") {
      writer.uint32(34).string(message.pass_threshold);
    }
    for (const v of message.questions) {
      Question.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Quiz {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuiz();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.quiz_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.article_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pass_threshold = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.questions.push(Question.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Quiz {
    return {
      quiz_id: isSet(object.quiz_id) ? globalThis.String(object.quiz_id) : "",
      article_id: isSet(object.article_id) ? globalThis.String(object.article_id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      pass_threshold: isSet(object.pass_threshold) ? globalThis.String(object.pass_threshold) : "",
      questions: globalThis.Array.isArray(object?.questions)
        ? object.questions.map((e: any) => Question.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Quiz): unknown {
    const obj: any = {};
    if (message.quiz_id !== "") {
      obj.quiz_id = message.quiz_id;
    }
    if (message.article_id !== "") {
      obj.article_id = message.article_id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.pass_threshold !== "") {
      obj.pass_threshold = message.pass_threshold;
    }
    if (message.questions?.length) {
      obj.questions = message.questions.map((e) => Question.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Quiz>, I>>(base?: I): Quiz {
    return Quiz.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Quiz>, I>>(object: I): Quiz {
    const message = createBaseQuiz();
    message.quiz_id = object.quiz_id ?? "";
    message.article_id = object.article_id ?? "";
    message.title = object.title ?? "";
    message.pass_threshold = object.pass_threshold ?? "";
    message.questions = object.questions?.map((e) => Question.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQuestion(): Question {
  return { question_id: "", prompt: "", options: [], weight: "" };
}

export const Question: MessageFns<Question> = {
  encode(message: Question, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.question_id !== "") {
      writer.uint32(10).string(message.question_id);
    }
    if (message.prompt !== "") {
      writer.uint32(18).string(message.prompt);
    }
    for (const v of message.options) {
      Option.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.weight !== "") {
      writer.uint32(34).string(message.weight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Question {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuestion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.question_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.options.push(Option.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.weight = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Question {
    return {
      question_id: isSet(object.question_id) ? globalThis.String(object.question_id) : "",
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
      options: globalThis.Array.isArray(object?.options) ? object.options.map((e: any) => Option.fromJSON(e)) : [],
      weight: isSet(object.weight) ? globalThis.String(object.weight) : "",
    };
  },

  toJSON(message: Question): unknown {
    const obj: any = {};
    if (message.question_id !== "") {
      obj.question_id = message.question_id;
    }
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    if (message.options?.length) {
      obj.options = message.options.map((e) => Option.toJSON(e));
    }
    if (message.weight !== "") {
      obj.weight = message.weight;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Question>, I>>(base?: I): Question {
    return Question.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Question>, I>>(object: I): Question {
    const message = createBaseQuestion();
    message.question_id = object.question_id ?? "";
    message.prompt = object.prompt ?? "";
    message.options = object.options?.map((e) => Option.fromPartial(e)) || [];
    message.weight = object.weight ?? "";
    return message;
  },
};

function createBaseOption(): Option {
  return { key: "", text: "" };
}

export const Option: MessageFns<Option> = {
  encode(message: Option, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Option {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOption();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Option {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
    };
  },

  toJSON(message: Option): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Option>, I>>(base?: I): Option {
    return Option.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Option>, I>>(object: I): Option {
    const message = createBaseOption();
    message.key = object.key ?? "";
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseGradeRequest(): GradeRequest {
  return { user_id: "", quiz_id: "", answers: {} };
}

export const GradeRequest: MessageFns<GradeRequest> = {
  encode(message: GradeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.quiz_id !== "") {
      writer.uint32(18).string(message.quiz_id);
    }
    Object.entries(message.answers).forEach(([key, value]) => {
      GradeRequest_AnswersEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GradeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGradeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.quiz_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = GradeRequest_AnswersEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.answers[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GradeRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      quiz_id: isSet(object.quiz_id) ? globalThis.String(object.quiz_id) : "",
      answers: isObject(object.answers)
        ? Object.entries(object.answers).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: GradeRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.quiz_id !== "") {
      obj.quiz_id = message.quiz_id;
    }
    if (message.answers) {
      const entries = Object.entries(message.answers);
      if (entries.length > 0) {
        obj.answers = {};
        entries.forEach(([k, v]) => {
          obj.answers[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GradeRequest>, I>>(base?: I): GradeRequest {
    return GradeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GradeRequest>, I>>(object: I): GradeRequest {
    const message = createBaseGradeRequest();
    message.user_id = object.user_id ?? "";
    message.quiz_id = object.quiz_id ?? "";
    message.answers = Object.entries(object.answers ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseGradeRequest_AnswersEntry(): GradeRequest_AnswersEntry {
  return { key: "", value: "" };
}

export const GradeRequest_AnswersEntry: MessageFns<GradeRequest_AnswersEntry> = {
  encode(message: GradeRequest_AnswersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GradeRequest_AnswersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGradeRequest_AnswersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GradeRequest_AnswersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: GradeRequest_AnswersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GradeRequest_AnswersEntry>, I>>(base?: I): GradeRequest_AnswersEntry {
    return GradeRequest_AnswersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GradeRequest_AnswersEntry>, I>>(object: I): GradeRequest_AnswersEntry {
    const message = createBaseGradeRequest_AnswersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseGradeResponse(): GradeResponse {
  return { attempt_id: "", attempt_no: 0, score: "", passed: false };
}

export const GradeResponse: MessageFns<GradeResponse> = {
  encode(message: GradeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attempt_id !== "") {
      writer.uint32(10).string(message.attempt_id);
    }
    if (message.attempt_no !== 0) {
      writer.uint32(16).int32(message.attempt_no);
    }
    if (message.score !== "") {
      writer.uint32(26).string(message.score);
    }
    if (message.passed !== false) {
      writer.uint32(32).bool(message.passed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GradeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGradeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attempt_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.attempt_no = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.score = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.passed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GradeResponse {
    return {
      attempt_id: isSet(object.attempt_id) ? globalThis.String(object.attempt_id) : "",
      attempt_no: isSet(object.attempt_no) ? globalThis.Number(object.attempt_no) : 0,
      score: isSet(object.score) ? globalThis.String(object.score) : "",
      passed: isSet(object.passed) ? globalThis.Boolean(object.passed) : false,
    };
  },

  toJSON(message: GradeResponse): unknown {
    const obj: any = {};
    if (message.attempt_id !== "") {
      obj.attempt_id = message.attempt_id;
    }
    if (message.attempt_no !== 0) {
      obj.attempt_no = Math.round(message.attempt_no);
    }
    if (message.score !== "") {
      obj.score = message.score;
    }
    if (message.passed !== false) {
      obj.passed = message.passed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GradeResponse>, I>>(base?: I): GradeResponse {
    return GradeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GradeResponse>, I>>(object: I): GradeResponse {
    const message = createBaseGradeResponse();
    message.attempt_id = object.attempt_id ?? "";
    message.attempt_no = object.attempt_no ?? 0;
    message.score = object.score ?? "";
    message.passed = object.passed ?? false;
    return message;
  },
};

function createBaseListAttemptsRequest(): ListAttemptsRequest {
  return { user_id: "", quiz_id: "", page: undefined };
}

export const ListAttemptsRequest: MessageFns<ListAttemptsRequest> = {
  encode(message: ListAttemptsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.quiz_id !== "") {
      writer.uint32(18).string(message.quiz_id);
    }
    if (message.page !== undefined) {
      PageRequest.encode(message.page, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAttemptsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAttemptsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.quiz_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.page = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAttemptsRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      quiz_id: isSet(object.quiz_id) ? globalThis.String(object.quiz_id) : "",
      page: isSet(object.page) ? PageRequest.fromJSON(object.page) : undefined,
    };
  },

  toJSON(message: ListAttemptsRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.quiz_id !== "") {
      obj.quiz_id = message.quiz_id;
    }
    if (message.page !== undefined) {
      obj.page = PageRequest.toJSON(message.page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAttemptsRequest>, I>>(base?: I): ListAttemptsRequest {
    return ListAttemptsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAttemptsRequest>, I>>(object: I): ListAttemptsRequest {
    const message = createBaseListAttemptsRequest();
    message.user_id = object.user_id ?? "";
    message.quiz_id = object.quiz_id ?? "";
    message.page = (object.page !== undefined && object.page !== null)
      ? PageRequest.fromPartial(object.page)
      : undefined;
    return message;
  },
};

function createBaseListAttemptsResponse(): ListAttemptsResponse {
  return { items: [], page: undefined };
}

export const ListAttemptsResponse: MessageFns<ListAttemptsResponse> = {
  encode(message: ListAttemptsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      ListAttemptsResponse_Attempt.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.page !== undefined) {
      PageResponse.encode(message.page, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAttemptsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAttemptsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(ListAttemptsResponse_Attempt.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.page = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAttemptsResponse {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => ListAttemptsResponse_Attempt.fromJSON(e))
        : [],
      page: isSet(object.page) ? PageResponse.fromJSON(object.page) : undefined,
    };
  },

  toJSON(message: ListAttemptsResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => ListAttemptsResponse_Attempt.toJSON(e));
    }
    if (message.page !== undefined) {
      obj.page = PageResponse.toJSON(message.page);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAttemptsResponse>, I>>(base?: I): ListAttemptsResponse {
    return ListAttemptsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAttemptsResponse>, I>>(object: I): ListAttemptsResponse {
    const message = createBaseListAttemptsResponse();
    message.items = object.items?.map((e) => ListAttemptsResponse_Attempt.fromPartial(e)) || [];
    message.page = (object.page !== undefined && object.page !== null)
      ? PageResponse.fromPartial(object.page)
      : undefined;
    return message;
  },
};

function createBaseListAttemptsResponse_Attempt(): ListAttemptsResponse_Attempt {
  return { attempt_id: "", attempt_no: 0, score: "", created_at: "" };
}

export const ListAttemptsResponse_Attempt: MessageFns<ListAttemptsResponse_Attempt> = {
  encode(message: ListAttemptsResponse_Attempt, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attempt_id !== "") {
      writer.uint32(10).string(message.attempt_id);
    }
    if (message.attempt_no !== 0) {
      writer.uint32(16).int32(message.attempt_no);
    }
    if (message.score !== "") {
      writer.uint32(26).string(message.score);
    }
    if (message.created_at !== "") {
      writer.uint32(34).string(message.created_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAttemptsResponse_Attempt {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAttemptsResponse_Attempt();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attempt_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.attempt_no = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.score = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAttemptsResponse_Attempt {
    return {
      attempt_id: isSet(object.attempt_id) ? globalThis.String(object.attempt_id) : "",
      attempt_no: isSet(object.attempt_no) ? globalThis.Number(object.attempt_no) : 0,
      score: isSet(object.score) ? globalThis.String(object.score) : "",
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : "",
    };
  },

  toJSON(message: ListAttemptsResponse_Attempt): unknown {
    const obj: any = {};
    if (message.attempt_id !== "") {
      obj.attempt_id = message.attempt_id;
    }
    if (message.attempt_no !== 0) {
      obj.attempt_no = Math.round(message.attempt_no);
    }
    if (message.score !== "") {
      obj.score = message.score;
    }
    if (message.created_at !== "") {
      obj.created_at = message.created_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAttemptsResponse_Attempt>, I>>(base?: I): ListAttemptsResponse_Attempt {
    return ListAttemptsResponse_Attempt.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAttemptsResponse_Attempt>, I>>(object: I): ListAttemptsResponse_Attempt {
    const message = createBaseListAttemptsResponse_Attempt();
    message.attempt_id = object.attempt_id ?? "";
    message.attempt_no = object.attempt_no ?? 0;
    message.score = object.score ?? "";
    message.created_at = object.created_at ?? "";
    return message;
  },
};

/**
 * Servicio de Aprendizaje (TypeScript + NestJS). Dueño de artículos, versiones,
 * cuestionarios e historial completo de intentos. Productor de eventos RabbitMQ
 * (publicación de contenido) consumidos por Auditoría/Notificación.
 */
export type LearningServiceService = typeof LearningServiceService;
export const LearningServiceService = {
  /** Curaduría (FR-007): editor crea/edita/versiona borradores y envía a revisión. */
  createDraft: {
    path: "/fintcart.learning.v1.LearningService/CreateDraft",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateDraftRequest) => Buffer.from(CreateDraftRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreateDraftRequest.decode(value),
    responseSerialize: (value: ArticleVersion) => Buffer.from(ArticleVersion.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ArticleVersion.decode(value),
  },
  updateDraft: {
    path: "/fintcart.learning.v1.LearningService/UpdateDraft",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateDraftRequest) => Buffer.from(UpdateDraftRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UpdateDraftRequest.decode(value),
    responseSerialize: (value: ArticleVersion) => Buffer.from(ArticleVersion.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ArticleVersion.decode(value),
  },
  submitForReview: {
    path: "/fintcart.learning.v1.LearningService/SubmitForReview",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VersionRef) => Buffer.from(VersionRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => VersionRef.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
  /** Aprobación/publicación (FR-008): SOLO coordinador editorial y ≠ editor creador. */
  approveAndPublish: {
    path: "/fintcart.learning.v1.LearningService/ApproveAndPublish",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ApprovePublishRequest) => Buffer.from(ApprovePublishRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ApprovePublishRequest.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
  archive: {
    path: "/fintcart.learning.v1.LearningService/Archive",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VersionRef) => Buffer.from(VersionRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => VersionRef.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
  /** Catálogo y lectura (FR-010, FR-011). Incrementa estadística de vista (FR-018). */
  listPublished: {
    path: "/fintcart.learning.v1.LearningService/ListPublished",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListPublishedRequest) => Buffer.from(ListPublishedRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ListPublishedRequest.decode(value),
    responseSerialize: (value: ListPublishedResponse) => Buffer.from(ListPublishedResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ListPublishedResponse.decode(value),
  },
  getArticle: {
    path: "/fintcart.learning.v1.LearningService/GetArticle",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ArticleRef) => Buffer.from(ArticleRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ArticleRef.decode(value),
    responseSerialize: (value: Article) => Buffer.from(Article.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Article.decode(value),
  },
  /** Cuestionarios (FR-009). */
  getQuiz: {
    path: "/fintcart.learning.v1.LearningService/GetQuiz",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: QuizRef) => Buffer.from(QuizRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => QuizRef.decode(value),
    responseSerialize: (value: Quiz) => Buffer.from(Quiz.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Quiz.decode(value),
  },
  /**
   * Calificación (FR-012/FR-016): persiste SIEMPRE el intento; lo invoca la Saga
   * de calificación (research D-07). Devuelve score y número de intento.
   */
  gradeAndStoreAttempt: {
    path: "/fintcart.learning.v1.LearningService/GradeAndStoreAttempt",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GradeRequest) => Buffer.from(GradeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GradeRequest.decode(value),
    responseSerialize: (value: GradeResponse) => Buffer.from(GradeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GradeResponse.decode(value),
  },
  listAttempts: {
    path: "/fintcart.learning.v1.LearningService/ListAttempts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListAttemptsRequest) => Buffer.from(ListAttemptsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ListAttemptsRequest.decode(value),
    responseSerialize: (value: ListAttemptsResponse) => Buffer.from(ListAttemptsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ListAttemptsResponse.decode(value),
  },
  /** Saga de anonimización (FR-030): disocia PII de los intentos del usuario. */
  anonymizeAttempts: {
    path: "/fintcart.learning.v1.LearningService/AnonymizeAttempts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserRef) => Buffer.from(UserRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserRef.decode(value),
    responseSerialize: (value: OpResult) => Buffer.from(OpResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => OpResult.decode(value),
  },
} as const;

export interface LearningServiceServer extends UntypedServiceImplementation {
  /** Curaduría (FR-007): editor crea/edita/versiona borradores y envía a revisión. */
  createDraft: handleUnaryCall<CreateDraftRequest, ArticleVersion>;
  updateDraft: handleUnaryCall<UpdateDraftRequest, ArticleVersion>;
  submitForReview: handleUnaryCall<VersionRef, OpResult>;
  /** Aprobación/publicación (FR-008): SOLO coordinador editorial y ≠ editor creador. */
  approveAndPublish: handleUnaryCall<ApprovePublishRequest, OpResult>;
  archive: handleUnaryCall<VersionRef, OpResult>;
  /** Catálogo y lectura (FR-010, FR-011). Incrementa estadística de vista (FR-018). */
  listPublished: handleUnaryCall<ListPublishedRequest, ListPublishedResponse>;
  getArticle: handleUnaryCall<ArticleRef, Article>;
  /** Cuestionarios (FR-009). */
  getQuiz: handleUnaryCall<QuizRef, Quiz>;
  /**
   * Calificación (FR-012/FR-016): persiste SIEMPRE el intento; lo invoca la Saga
   * de calificación (research D-07). Devuelve score y número de intento.
   */
  gradeAndStoreAttempt: handleUnaryCall<GradeRequest, GradeResponse>;
  listAttempts: handleUnaryCall<ListAttemptsRequest, ListAttemptsResponse>;
  /** Saga de anonimización (FR-030): disocia PII de los intentos del usuario. */
  anonymizeAttempts: handleUnaryCall<UserRef, OpResult>;
}

export interface LearningServiceClient extends Client {
  /** Curaduría (FR-007): editor crea/edita/versiona borradores y envía a revisión. */
  createDraft(
    request: CreateDraftRequest,
    callback: (error: ServiceError | null, response: ArticleVersion) => void,
  ): ClientUnaryCall;
  createDraft(
    request: CreateDraftRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArticleVersion) => void,
  ): ClientUnaryCall;
  createDraft(
    request: CreateDraftRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArticleVersion) => void,
  ): ClientUnaryCall;
  updateDraft(
    request: UpdateDraftRequest,
    callback: (error: ServiceError | null, response: ArticleVersion) => void,
  ): ClientUnaryCall;
  updateDraft(
    request: UpdateDraftRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArticleVersion) => void,
  ): ClientUnaryCall;
  updateDraft(
    request: UpdateDraftRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArticleVersion) => void,
  ): ClientUnaryCall;
  submitForReview(
    request: VersionRef,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  submitForReview(
    request: VersionRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  submitForReview(
    request: VersionRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  /** Aprobación/publicación (FR-008): SOLO coordinador editorial y ≠ editor creador. */
  approveAndPublish(
    request: ApprovePublishRequest,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  approveAndPublish(
    request: ApprovePublishRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  approveAndPublish(
    request: ApprovePublishRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  archive(request: VersionRef, callback: (error: ServiceError | null, response: OpResult) => void): ClientUnaryCall;
  archive(
    request: VersionRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  archive(
    request: VersionRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  /** Catálogo y lectura (FR-010, FR-011). Incrementa estadística de vista (FR-018). */
  listPublished(
    request: ListPublishedRequest,
    callback: (error: ServiceError | null, response: ListPublishedResponse) => void,
  ): ClientUnaryCall;
  listPublished(
    request: ListPublishedRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListPublishedResponse) => void,
  ): ClientUnaryCall;
  listPublished(
    request: ListPublishedRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListPublishedResponse) => void,
  ): ClientUnaryCall;
  getArticle(request: ArticleRef, callback: (error: ServiceError | null, response: Article) => void): ClientUnaryCall;
  getArticle(
    request: ArticleRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Article) => void,
  ): ClientUnaryCall;
  getArticle(
    request: ArticleRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Article) => void,
  ): ClientUnaryCall;
  /** Cuestionarios (FR-009). */
  getQuiz(request: QuizRef, callback: (error: ServiceError | null, response: Quiz) => void): ClientUnaryCall;
  getQuiz(
    request: QuizRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Quiz) => void,
  ): ClientUnaryCall;
  getQuiz(
    request: QuizRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Quiz) => void,
  ): ClientUnaryCall;
  /**
   * Calificación (FR-012/FR-016): persiste SIEMPRE el intento; lo invoca la Saga
   * de calificación (research D-07). Devuelve score y número de intento.
   */
  gradeAndStoreAttempt(
    request: GradeRequest,
    callback: (error: ServiceError | null, response: GradeResponse) => void,
  ): ClientUnaryCall;
  gradeAndStoreAttempt(
    request: GradeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GradeResponse) => void,
  ): ClientUnaryCall;
  gradeAndStoreAttempt(
    request: GradeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GradeResponse) => void,
  ): ClientUnaryCall;
  listAttempts(
    request: ListAttemptsRequest,
    callback: (error: ServiceError | null, response: ListAttemptsResponse) => void,
  ): ClientUnaryCall;
  listAttempts(
    request: ListAttemptsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListAttemptsResponse) => void,
  ): ClientUnaryCall;
  listAttempts(
    request: ListAttemptsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListAttemptsResponse) => void,
  ): ClientUnaryCall;
  /** Saga de anonimización (FR-030): disocia PII de los intentos del usuario. */
  anonymizeAttempts(
    request: UserRef,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  anonymizeAttempts(
    request: UserRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
  anonymizeAttempts(
    request: UserRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: OpResult) => void,
  ): ClientUnaryCall;
}

export const LearningServiceClient = makeGenericClientConstructor(
  LearningServiceService,
  "fintcart.learning.v1.LearningService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): LearningServiceClient;
  service: typeof LearningServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
