// This file is @generated by prost-build.
/// Dinero: monto decimal + código ISO-4217 (por defecto COP).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Money {
    /// \[decimal\] p. ej. "1500000.00"
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
    /// p. ej. "COP"
    #[prost(string, tag = "2")]
    pub currency: ::prost::alloc::string::String,
}
/// Paginación estándar para listados de solo lectura.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PageRequest {
    #[prost(int32, tag = "1")]
    pub page_size: i32,
    #[prost(string, tag = "2")]
    pub page_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PageResponse {
    #[prost(string, tag = "1")]
    pub next_page_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub total_size: i64,
}
/// Marca temporal en RFC-3339 UTC como string para evitar ambigüedad de zona.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Timestamp {
    /// p. ej. "2026-06-13T15:04:05Z"
    #[prost(string, tag = "1")]
    pub rfc3339: ::prost::alloc::string::String,
}
/// Resultado genérico de una operación de comando.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpResult {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// código de error de dominio si aplica
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
