// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: fintcart/orchestrator/v1/orchestrator.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { CalcType, calcTypeFromJSON, calcTypeToJSON } from "../../simulator/v1/simulator";

export const protobufPackage = "fintcart.orchestrator.v1";

export interface UserRef {
  user_id: string;
}

export interface CalculatorApprovalRequest {
  calculator_id: string;
  /**
   * Coordinador editorial, y DISTINTO del autor (FR-053). El rol lo exige el borde, que
   * es el único sitio de la plataforma que conoce los roles; la separación de autoría la
   * imponen el Simulador y la base.
   */
  coordinator_id: string;
}

export interface CalculatorApprovalResult {
  calculator_id: string;
  /**
   * Versión que esta aprobación publicó. El autor puede haber escrito versiones nuevas
   * mientras la propuesta esperaba, y la que se publica es la que se revisó.
   */
  version: number;
}

export interface SagaHandle {
  saga_id: string;
}

export interface SagaStatus {
  saga_id: string;
  saga_type: string;
  /** running | completed | compensating | failed */
  status: string;
  current_step: number;
}

export interface StartRegistrationRequest {
  email: string;
  password: string;
  display_name: string;
}

export interface EmailVerificationRequest {
  user_id: string;
  verification_token: string;
}

export interface QuizGradingRequest {
  user_id: string;
  quiz_id: string;
  answers: { [key: string]: string };
  /**
   * Sesión emitida por `Learning.StartQuizSession` (FR-038…FR-042). Obligatoria:
   * el intento solo se califica contra las preguntas servidas en esta sesión.
   */
  session_id: string;
}

export interface QuizGradingRequest_AnswersEntry {
  key: string;
  value: string;
}

export interface QuizGradingResult {
  attempt_id: string;
  attempt_no: number;
  /** [decimal] */
  score: string;
  passed: boolean;
  /** progreso resultante */
  points_after: number;
}

export interface SimulationRequest {
  user_id: string;
  /**
   * CAMBIO DE CONTRATO (FR-043): `calc_type` identifica una calculadora NATIVA.
   *
   * Reutiliza el enum del contrato del Simulador en lugar de un `int32` con el
   * tipo indicado en un comentario: si CalcType gana un valor, un entero suelto
   * seguiría aceptando cualquier número y el desajuste solo aparecería en
   * ejecución. El cambio es compatible a nivel de cable (ambos son varint).
   *
   * Es EXCLUYENTE con `calculator_id`, igual que en `ComputeRequest`: una
   * ejecución se identifica por el tipo nativo o por la definición, nunca por
   * los dos. El Simulador rechaza la petición que traiga ambos, así que un
   * llamador que los rellene por descuido falla de forma visible en vez de que
   * uno de los dos se ignore en silencio.
   */
  calc_type: CalcType;
  currency: string;
  /** [decimal] */
  inputs: { [key: string]: string };
  /**
   * Calculadora DEFINIDA por un usuario (FR-043, camino preferente). Es lo que
   * permite que `/calculators/{id}/run` recorra esta misma saga en vez de llamar
   * al Simulador por su cuenta: la ejecución queda auditada (FR-025, D-03) porque
   * el único productor de `simulation.executed` es este servicio.
   *
   * Vacío ⇒ la ejecución va por `calc_type`.
   */
  calculator_id: string;
}

export interface SimulationRequest_InputsEntry {
  key: string;
  value: string;
}

export interface SimulationResult {
  simulation_id: string;
  /** [decimal] */
  result: { [key: string]: string };
  /**
   * Procedencia de la ejecución (FR-050, FR-058). Faltaban, y su ausencia hacía que la
   * respuesta de `POST /calculators/{id}/run` no pudiera explicarse: el delta REST promete
   * «`calculator_version` e `indicators_used`» y el historial los lleva, así que la única
   * ejecución que no los devolvía era justo la que el usuario acaba de lanzar.
   *
   * La versión dice CON QUÉ definición se calculó —una calculadora cambia con el tiempo, y sin
   * la versión un resultado de hace un año se explicaría con la fórmula de hoy—, y los
   * indicadores son los valores que se usaron ese día, resueltos a la fecha de ejecución.
   */
  calculator_version: number;
  /** [decimal] */
  indicators_used: { [key: string]: string };
}

export interface SimulationResult_ResultEntry {
  key: string;
  value: string;
}

export interface SimulationResult_IndicatorsUsedEntry {
  key: string;
  value: string;
}

function createBaseUserRef(): UserRef {
  return { user_id: "" };
}

export const UserRef: MessageFns<UserRef> = {
  encode(message: UserRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRef {
    return { user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "" };
  },

  toJSON(message: UserRef): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRef>, I>>(base?: I): UserRef {
    return UserRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRef>, I>>(object: I): UserRef {
    const message = createBaseUserRef();
    message.user_id = object.user_id ?? "";
    return message;
  },
};

function createBaseCalculatorApprovalRequest(): CalculatorApprovalRequest {
  return { calculator_id: "", coordinator_id: "" };
}

export const CalculatorApprovalRequest: MessageFns<CalculatorApprovalRequest> = {
  encode(message: CalculatorApprovalRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.calculator_id !== "") {
      writer.uint32(10).string(message.calculator_id);
    }
    if (message.coordinator_id !== "") {
      writer.uint32(18).string(message.coordinator_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculatorApprovalRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculatorApprovalRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.calculator_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.coordinator_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculatorApprovalRequest {
    return {
      calculator_id: isSet(object.calculator_id) ? globalThis.String(object.calculator_id) : "",
      coordinator_id: isSet(object.coordinator_id) ? globalThis.String(object.coordinator_id) : "",
    };
  },

  toJSON(message: CalculatorApprovalRequest): unknown {
    const obj: any = {};
    if (message.calculator_id !== "") {
      obj.calculator_id = message.calculator_id;
    }
    if (message.coordinator_id !== "") {
      obj.coordinator_id = message.coordinator_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculatorApprovalRequest>, I>>(base?: I): CalculatorApprovalRequest {
    return CalculatorApprovalRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculatorApprovalRequest>, I>>(object: I): CalculatorApprovalRequest {
    const message = createBaseCalculatorApprovalRequest();
    message.calculator_id = object.calculator_id ?? "";
    message.coordinator_id = object.coordinator_id ?? "";
    return message;
  },
};

function createBaseCalculatorApprovalResult(): CalculatorApprovalResult {
  return { calculator_id: "", version: 0 };
}

export const CalculatorApprovalResult: MessageFns<CalculatorApprovalResult> = {
  encode(message: CalculatorApprovalResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.calculator_id !== "") {
      writer.uint32(10).string(message.calculator_id);
    }
    if (message.version !== 0) {
      writer.uint32(16).int32(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculatorApprovalResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculatorApprovalResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.calculator_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculatorApprovalResult {
    return {
      calculator_id: isSet(object.calculator_id) ? globalThis.String(object.calculator_id) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: CalculatorApprovalResult): unknown {
    const obj: any = {};
    if (message.calculator_id !== "") {
      obj.calculator_id = message.calculator_id;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculatorApprovalResult>, I>>(base?: I): CalculatorApprovalResult {
    return CalculatorApprovalResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculatorApprovalResult>, I>>(object: I): CalculatorApprovalResult {
    const message = createBaseCalculatorApprovalResult();
    message.calculator_id = object.calculator_id ?? "";
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseSagaHandle(): SagaHandle {
  return { saga_id: "" };
}

export const SagaHandle: MessageFns<SagaHandle> = {
  encode(message: SagaHandle, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.saga_id !== "") {
      writer.uint32(10).string(message.saga_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SagaHandle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSagaHandle();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.saga_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SagaHandle {
    return { saga_id: isSet(object.saga_id) ? globalThis.String(object.saga_id) : "" };
  },

  toJSON(message: SagaHandle): unknown {
    const obj: any = {};
    if (message.saga_id !== "") {
      obj.saga_id = message.saga_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SagaHandle>, I>>(base?: I): SagaHandle {
    return SagaHandle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SagaHandle>, I>>(object: I): SagaHandle {
    const message = createBaseSagaHandle();
    message.saga_id = object.saga_id ?? "";
    return message;
  },
};

function createBaseSagaStatus(): SagaStatus {
  return { saga_id: "", saga_type: "", status: "", current_step: 0 };
}

export const SagaStatus: MessageFns<SagaStatus> = {
  encode(message: SagaStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.saga_id !== "") {
      writer.uint32(10).string(message.saga_id);
    }
    if (message.saga_type !== "") {
      writer.uint32(18).string(message.saga_type);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.current_step !== 0) {
      writer.uint32(32).int32(message.current_step);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SagaStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSagaStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.saga_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.saga_type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.current_step = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SagaStatus {
    return {
      saga_id: isSet(object.saga_id) ? globalThis.String(object.saga_id) : "",
      saga_type: isSet(object.saga_type) ? globalThis.String(object.saga_type) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      current_step: isSet(object.current_step) ? globalThis.Number(object.current_step) : 0,
    };
  },

  toJSON(message: SagaStatus): unknown {
    const obj: any = {};
    if (message.saga_id !== "") {
      obj.saga_id = message.saga_id;
    }
    if (message.saga_type !== "") {
      obj.saga_type = message.saga_type;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.current_step !== 0) {
      obj.current_step = Math.round(message.current_step);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SagaStatus>, I>>(base?: I): SagaStatus {
    return SagaStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SagaStatus>, I>>(object: I): SagaStatus {
    const message = createBaseSagaStatus();
    message.saga_id = object.saga_id ?? "";
    message.saga_type = object.saga_type ?? "";
    message.status = object.status ?? "";
    message.current_step = object.current_step ?? 0;
    return message;
  },
};

function createBaseStartRegistrationRequest(): StartRegistrationRequest {
  return { email: "", password: "", display_name: "" };
}

export const StartRegistrationRequest: MessageFns<StartRegistrationRequest> = {
  encode(message: StartRegistrationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.display_name !== "") {
      writer.uint32(26).string(message.display_name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartRegistrationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartRegistrationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.display_name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartRegistrationRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      display_name: isSet(object.display_name) ? globalThis.String(object.display_name) : "",
    };
  },

  toJSON(message: StartRegistrationRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.display_name !== "") {
      obj.display_name = message.display_name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StartRegistrationRequest>, I>>(base?: I): StartRegistrationRequest {
    return StartRegistrationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartRegistrationRequest>, I>>(object: I): StartRegistrationRequest {
    const message = createBaseStartRegistrationRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    message.display_name = object.display_name ?? "";
    return message;
  },
};

function createBaseEmailVerificationRequest(): EmailVerificationRequest {
  return { user_id: "", verification_token: "" };
}

export const EmailVerificationRequest: MessageFns<EmailVerificationRequest> = {
  encode(message: EmailVerificationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.verification_token !== "") {
      writer.uint32(18).string(message.verification_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailVerificationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailVerificationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.verification_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailVerificationRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      verification_token: isSet(object.verification_token) ? globalThis.String(object.verification_token) : "",
    };
  },

  toJSON(message: EmailVerificationRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.verification_token !== "") {
      obj.verification_token = message.verification_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailVerificationRequest>, I>>(base?: I): EmailVerificationRequest {
    return EmailVerificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailVerificationRequest>, I>>(object: I): EmailVerificationRequest {
    const message = createBaseEmailVerificationRequest();
    message.user_id = object.user_id ?? "";
    message.verification_token = object.verification_token ?? "";
    return message;
  },
};

function createBaseQuizGradingRequest(): QuizGradingRequest {
  return { user_id: "", quiz_id: "", answers: {}, session_id: "" };
}

export const QuizGradingRequest: MessageFns<QuizGradingRequest> = {
  encode(message: QuizGradingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.quiz_id !== "") {
      writer.uint32(18).string(message.quiz_id);
    }
    Object.entries(message.answers).forEach(([key, value]) => {
      QuizGradingRequest_AnswersEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.session_id !== "") {
      writer.uint32(34).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuizGradingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuizGradingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.quiz_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = QuizGradingRequest_AnswersEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.answers[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuizGradingRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      quiz_id: isSet(object.quiz_id) ? globalThis.String(object.quiz_id) : "",
      answers: isObject(object.answers)
        ? Object.entries(object.answers).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
    };
  },

  toJSON(message: QuizGradingRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.quiz_id !== "") {
      obj.quiz_id = message.quiz_id;
    }
    if (message.answers) {
      const entries = Object.entries(message.answers);
      if (entries.length > 0) {
        obj.answers = {};
        entries.forEach(([k, v]) => {
          obj.answers[k] = v;
        });
      }
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuizGradingRequest>, I>>(base?: I): QuizGradingRequest {
    return QuizGradingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuizGradingRequest>, I>>(object: I): QuizGradingRequest {
    const message = createBaseQuizGradingRequest();
    message.user_id = object.user_id ?? "";
    message.quiz_id = object.quiz_id ?? "";
    message.answers = Object.entries(object.answers ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.session_id = object.session_id ?? "";
    return message;
  },
};

function createBaseQuizGradingRequest_AnswersEntry(): QuizGradingRequest_AnswersEntry {
  return { key: "", value: "" };
}

export const QuizGradingRequest_AnswersEntry: MessageFns<QuizGradingRequest_AnswersEntry> = {
  encode(message: QuizGradingRequest_AnswersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuizGradingRequest_AnswersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuizGradingRequest_AnswersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuizGradingRequest_AnswersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: QuizGradingRequest_AnswersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuizGradingRequest_AnswersEntry>, I>>(base?: I): QuizGradingRequest_AnswersEntry {
    return QuizGradingRequest_AnswersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuizGradingRequest_AnswersEntry>, I>>(
    object: I,
  ): QuizGradingRequest_AnswersEntry {
    const message = createBaseQuizGradingRequest_AnswersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseQuizGradingResult(): QuizGradingResult {
  return { attempt_id: "", attempt_no: 0, score: "", passed: false, points_after: 0 };
}

export const QuizGradingResult: MessageFns<QuizGradingResult> = {
  encode(message: QuizGradingResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attempt_id !== "") {
      writer.uint32(10).string(message.attempt_id);
    }
    if (message.attempt_no !== 0) {
      writer.uint32(16).int32(message.attempt_no);
    }
    if (message.score !== "") {
      writer.uint32(26).string(message.score);
    }
    if (message.passed !== false) {
      writer.uint32(32).bool(message.passed);
    }
    if (message.points_after !== 0) {
      writer.uint32(40).int32(message.points_after);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuizGradingResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuizGradingResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attempt_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.attempt_no = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.score = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.passed = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.points_after = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuizGradingResult {
    return {
      attempt_id: isSet(object.attempt_id) ? globalThis.String(object.attempt_id) : "",
      attempt_no: isSet(object.attempt_no) ? globalThis.Number(object.attempt_no) : 0,
      score: isSet(object.score) ? globalThis.String(object.score) : "",
      passed: isSet(object.passed) ? globalThis.Boolean(object.passed) : false,
      points_after: isSet(object.points_after) ? globalThis.Number(object.points_after) : 0,
    };
  },

  toJSON(message: QuizGradingResult): unknown {
    const obj: any = {};
    if (message.attempt_id !== "") {
      obj.attempt_id = message.attempt_id;
    }
    if (message.attempt_no !== 0) {
      obj.attempt_no = Math.round(message.attempt_no);
    }
    if (message.score !== "") {
      obj.score = message.score;
    }
    if (message.passed !== false) {
      obj.passed = message.passed;
    }
    if (message.points_after !== 0) {
      obj.points_after = Math.round(message.points_after);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuizGradingResult>, I>>(base?: I): QuizGradingResult {
    return QuizGradingResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuizGradingResult>, I>>(object: I): QuizGradingResult {
    const message = createBaseQuizGradingResult();
    message.attempt_id = object.attempt_id ?? "";
    message.attempt_no = object.attempt_no ?? 0;
    message.score = object.score ?? "";
    message.passed = object.passed ?? false;
    message.points_after = object.points_after ?? 0;
    return message;
  },
};

function createBaseSimulationRequest(): SimulationRequest {
  return { user_id: "", calc_type: 0, currency: "", inputs: {}, calculator_id: "" };
}

export const SimulationRequest: MessageFns<SimulationRequest> = {
  encode(message: SimulationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.calc_type !== 0) {
      writer.uint32(16).int32(message.calc_type);
    }
    if (message.currency !== "") {
      writer.uint32(26).string(message.currency);
    }
    Object.entries(message.inputs).forEach(([key, value]) => {
      SimulationRequest_InputsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.calculator_id !== "") {
      writer.uint32(42).string(message.calculator_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimulationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimulationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.calc_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = SimulationRequest_InputsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.inputs[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.calculator_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimulationRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      calc_type: isSet(object.calc_type) ? calcTypeFromJSON(object.calc_type) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      inputs: isObject(object.inputs)
        ? Object.entries(object.inputs).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      calculator_id: isSet(object.calculator_id) ? globalThis.String(object.calculator_id) : "",
    };
  },

  toJSON(message: SimulationRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.calc_type !== 0) {
      obj.calc_type = calcTypeToJSON(message.calc_type);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.inputs) {
      const entries = Object.entries(message.inputs);
      if (entries.length > 0) {
        obj.inputs = {};
        entries.forEach(([k, v]) => {
          obj.inputs[k] = v;
        });
      }
    }
    if (message.calculator_id !== "") {
      obj.calculator_id = message.calculator_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimulationRequest>, I>>(base?: I): SimulationRequest {
    return SimulationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimulationRequest>, I>>(object: I): SimulationRequest {
    const message = createBaseSimulationRequest();
    message.user_id = object.user_id ?? "";
    message.calc_type = object.calc_type ?? 0;
    message.currency = object.currency ?? "";
    message.inputs = Object.entries(object.inputs ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.calculator_id = object.calculator_id ?? "";
    return message;
  },
};

function createBaseSimulationRequest_InputsEntry(): SimulationRequest_InputsEntry {
  return { key: "", value: "" };
}

export const SimulationRequest_InputsEntry: MessageFns<SimulationRequest_InputsEntry> = {
  encode(message: SimulationRequest_InputsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimulationRequest_InputsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimulationRequest_InputsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimulationRequest_InputsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SimulationRequest_InputsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimulationRequest_InputsEntry>, I>>(base?: I): SimulationRequest_InputsEntry {
    return SimulationRequest_InputsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimulationRequest_InputsEntry>, I>>(
    object: I,
  ): SimulationRequest_InputsEntry {
    const message = createBaseSimulationRequest_InputsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseSimulationResult(): SimulationResult {
  return { simulation_id: "", result: {}, calculator_version: 0, indicators_used: {} };
}

export const SimulationResult: MessageFns<SimulationResult> = {
  encode(message: SimulationResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.simulation_id !== "") {
      writer.uint32(10).string(message.simulation_id);
    }
    Object.entries(message.result).forEach(([key, value]) => {
      SimulationResult_ResultEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    if (message.calculator_version !== 0) {
      writer.uint32(24).int32(message.calculator_version);
    }
    Object.entries(message.indicators_used).forEach(([key, value]) => {
      SimulationResult_IndicatorsUsedEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimulationResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimulationResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.simulation_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = SimulationResult_ResultEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.result[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.calculator_version = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = SimulationResult_IndicatorsUsedEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.indicators_used[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimulationResult {
    return {
      simulation_id: isSet(object.simulation_id) ? globalThis.String(object.simulation_id) : "",
      result: isObject(object.result)
        ? Object.entries(object.result).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      calculator_version: isSet(object.calculator_version) ? globalThis.Number(object.calculator_version) : 0,
      indicators_used: isObject(object.indicators_used)
        ? Object.entries(object.indicators_used).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: SimulationResult): unknown {
    const obj: any = {};
    if (message.simulation_id !== "") {
      obj.simulation_id = message.simulation_id;
    }
    if (message.result) {
      const entries = Object.entries(message.result);
      if (entries.length > 0) {
        obj.result = {};
        entries.forEach(([k, v]) => {
          obj.result[k] = v;
        });
      }
    }
    if (message.calculator_version !== 0) {
      obj.calculator_version = Math.round(message.calculator_version);
    }
    if (message.indicators_used) {
      const entries = Object.entries(message.indicators_used);
      if (entries.length > 0) {
        obj.indicators_used = {};
        entries.forEach(([k, v]) => {
          obj.indicators_used[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimulationResult>, I>>(base?: I): SimulationResult {
    return SimulationResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimulationResult>, I>>(object: I): SimulationResult {
    const message = createBaseSimulationResult();
    message.simulation_id = object.simulation_id ?? "";
    message.result = Object.entries(object.result ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.calculator_version = object.calculator_version ?? 0;
    message.indicators_used = Object.entries(object.indicators_used ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseSimulationResult_ResultEntry(): SimulationResult_ResultEntry {
  return { key: "", value: "" };
}

export const SimulationResult_ResultEntry: MessageFns<SimulationResult_ResultEntry> = {
  encode(message: SimulationResult_ResultEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimulationResult_ResultEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimulationResult_ResultEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimulationResult_ResultEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SimulationResult_ResultEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimulationResult_ResultEntry>, I>>(base?: I): SimulationResult_ResultEntry {
    return SimulationResult_ResultEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimulationResult_ResultEntry>, I>>(object: I): SimulationResult_ResultEntry {
    const message = createBaseSimulationResult_ResultEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseSimulationResult_IndicatorsUsedEntry(): SimulationResult_IndicatorsUsedEntry {
  return { key: "", value: "" };
}

export const SimulationResult_IndicatorsUsedEntry: MessageFns<SimulationResult_IndicatorsUsedEntry> = {
  encode(message: SimulationResult_IndicatorsUsedEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimulationResult_IndicatorsUsedEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimulationResult_IndicatorsUsedEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimulationResult_IndicatorsUsedEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SimulationResult_IndicatorsUsedEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimulationResult_IndicatorsUsedEntry>, I>>(
    base?: I,
  ): SimulationResult_IndicatorsUsedEntry {
    return SimulationResult_IndicatorsUsedEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimulationResult_IndicatorsUsedEntry>, I>>(
    object: I,
  ): SimulationResult_IndicatorsUsedEntry {
    const message = createBaseSimulationResult_IndicatorsUsedEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

/**
 * Orquestador (Go). Coordina Sagas y compensaciones (Constitución Principio VI).
 * SIN lógica de dominio: solo secuencia pasos gRPC y publica eventos (productor
 * RabbitMQ → Auditoría/Notificación). Invocado por el API Gateway para flujos
 * que cruzan ≥ 2 servicios.
 */
export type OrchestratorServiceService = typeof OrchestratorServiceService;
export const OrchestratorServiceService = {
  /** Saga de registro (D-04): Users.CreateProfile + Auth.CreateCredential + email. */
  startRegistration: {
    path: "/fintcart.orchestrator.v1.OrchestratorService/StartRegistration",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: StartRegistrationRequest) => Buffer.from(StartRegistrationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => StartRegistrationRequest.decode(value),
    responseSerialize: (value: SagaHandle) => Buffer.from(SagaHandle.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SagaHandle.decode(value),
  },
  /** Saga de verificación de correo: Users.MarkEmailVerified + Auth.ActivateCredential. */
  startEmailVerification: {
    path: "/fintcart.orchestrator.v1.OrchestratorService/StartEmailVerification",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EmailVerificationRequest) => Buffer.from(EmailVerificationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => EmailVerificationRequest.decode(value),
    responseSerialize: (value: SagaHandle) => Buffer.from(SagaHandle.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SagaHandle.decode(value),
  },
  /**
   * Saga de calificación (D-07): Learning.GradeAndStoreAttempt + Users.ApplyQuizScore
   * + eventos QuizGraded(→Audit) y de actividad(→Notificación/in-app).
   */
  startQuizGrading: {
    path: "/fintcart.orchestrator.v1.OrchestratorService/StartQuizGrading",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: QuizGradingRequest) => Buffer.from(QuizGradingRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => QuizGradingRequest.decode(value),
    responseSerialize: (value: QuizGradingResult) => Buffer.from(QuizGradingResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => QuizGradingResult.decode(value),
  },
  /** Simulación mediada para auditoría (D-03): Simulator.Compute + evento SimulationExecuted. */
  startSimulation: {
    path: "/fintcart.orchestrator.v1.OrchestratorService/StartSimulation",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SimulationRequest) => Buffer.from(SimulationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SimulationRequest.decode(value),
    responseSerialize: (value: SimulationResult) => Buffer.from(SimulationResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SimulationResult.decode(value),
  },
  /**
   * Saga de anonimización (FR-030/D-08): anonimiza Auth/Users/Learning/Simulator;
   * preserva Auditoría con actor_ref opaco.
   */
  startAccountAnonymization: {
    path: "/fintcart.orchestrator.v1.OrchestratorService/StartAccountAnonymization",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserRef) => Buffer.from(UserRef.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserRef.decode(value),
    responseSerialize: (value: SagaHandle) => Buffer.from(SagaHandle.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SagaHandle.decode(value),
  },
  /**
   * Aprobación de una calculadora al catálogo público (FR-053).
   *
   * Va por el Orquestador y no directo al Simulador por el mismo motivo que
   * `StartSimulation`: el Simulador NO es productor de eventos (Principio V) y la
   * aprobación tiene que quedar auditada. `calculator.published` es el rastro de quién
   * aprobó qué versión y cuándo, y sin él una calculadora aparecería en el catálogo sin
   * que nada diga cómo llegó.
   *
   * SÍNCRONA, como `StartSimulation`, y no un `SagaHandle`: el coordinador está esperando
   * el resultado de un clic, y devolverle un identificador de saga al que después preguntar
   * añadiría una consulta para una operación que dura una llamada.
   */
  approveCalculator: {
    path: "/fintcart.orchestrator.v1.OrchestratorService/ApproveCalculator",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CalculatorApprovalRequest) =>
      Buffer.from(CalculatorApprovalRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CalculatorApprovalRequest.decode(value),
    responseSerialize: (value: CalculatorApprovalResult) =>
      Buffer.from(CalculatorApprovalResult.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CalculatorApprovalResult.decode(value),
  },
  /** Consulta de estado de una saga. */
  getSagaStatus: {
    path: "/fintcart.orchestrator.v1.OrchestratorService/GetSagaStatus",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SagaHandle) => Buffer.from(SagaHandle.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SagaHandle.decode(value),
    responseSerialize: (value: SagaStatus) => Buffer.from(SagaStatus.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SagaStatus.decode(value),
  },
} as const;

export interface OrchestratorServiceServer extends UntypedServiceImplementation {
  /** Saga de registro (D-04): Users.CreateProfile + Auth.CreateCredential + email. */
  startRegistration: handleUnaryCall<StartRegistrationRequest, SagaHandle>;
  /** Saga de verificación de correo: Users.MarkEmailVerified + Auth.ActivateCredential. */
  startEmailVerification: handleUnaryCall<EmailVerificationRequest, SagaHandle>;
  /**
   * Saga de calificación (D-07): Learning.GradeAndStoreAttempt + Users.ApplyQuizScore
   * + eventos QuizGraded(→Audit) y de actividad(→Notificación/in-app).
   */
  startQuizGrading: handleUnaryCall<QuizGradingRequest, QuizGradingResult>;
  /** Simulación mediada para auditoría (D-03): Simulator.Compute + evento SimulationExecuted. */
  startSimulation: handleUnaryCall<SimulationRequest, SimulationResult>;
  /**
   * Saga de anonimización (FR-030/D-08): anonimiza Auth/Users/Learning/Simulator;
   * preserva Auditoría con actor_ref opaco.
   */
  startAccountAnonymization: handleUnaryCall<UserRef, SagaHandle>;
  /**
   * Aprobación de una calculadora al catálogo público (FR-053).
   *
   * Va por el Orquestador y no directo al Simulador por el mismo motivo que
   * `StartSimulation`: el Simulador NO es productor de eventos (Principio V) y la
   * aprobación tiene que quedar auditada. `calculator.published` es el rastro de quién
   * aprobó qué versión y cuándo, y sin él una calculadora aparecería en el catálogo sin
   * que nada diga cómo llegó.
   *
   * SÍNCRONA, como `StartSimulation`, y no un `SagaHandle`: el coordinador está esperando
   * el resultado de un clic, y devolverle un identificador de saga al que después preguntar
   * añadiría una consulta para una operación que dura una llamada.
   */
  approveCalculator: handleUnaryCall<CalculatorApprovalRequest, CalculatorApprovalResult>;
  /** Consulta de estado de una saga. */
  getSagaStatus: handleUnaryCall<SagaHandle, SagaStatus>;
}

export interface OrchestratorServiceClient extends Client {
  /** Saga de registro (D-04): Users.CreateProfile + Auth.CreateCredential + email. */
  startRegistration(
    request: StartRegistrationRequest,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  startRegistration(
    request: StartRegistrationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  startRegistration(
    request: StartRegistrationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  /** Saga de verificación de correo: Users.MarkEmailVerified + Auth.ActivateCredential. */
  startEmailVerification(
    request: EmailVerificationRequest,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  startEmailVerification(
    request: EmailVerificationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  startEmailVerification(
    request: EmailVerificationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  /**
   * Saga de calificación (D-07): Learning.GradeAndStoreAttempt + Users.ApplyQuizScore
   * + eventos QuizGraded(→Audit) y de actividad(→Notificación/in-app).
   */
  startQuizGrading(
    request: QuizGradingRequest,
    callback: (error: ServiceError | null, response: QuizGradingResult) => void,
  ): ClientUnaryCall;
  startQuizGrading(
    request: QuizGradingRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: QuizGradingResult) => void,
  ): ClientUnaryCall;
  startQuizGrading(
    request: QuizGradingRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: QuizGradingResult) => void,
  ): ClientUnaryCall;
  /** Simulación mediada para auditoría (D-03): Simulator.Compute + evento SimulationExecuted. */
  startSimulation(
    request: SimulationRequest,
    callback: (error: ServiceError | null, response: SimulationResult) => void,
  ): ClientUnaryCall;
  startSimulation(
    request: SimulationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SimulationResult) => void,
  ): ClientUnaryCall;
  startSimulation(
    request: SimulationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SimulationResult) => void,
  ): ClientUnaryCall;
  /**
   * Saga de anonimización (FR-030/D-08): anonimiza Auth/Users/Learning/Simulator;
   * preserva Auditoría con actor_ref opaco.
   */
  startAccountAnonymization(
    request: UserRef,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  startAccountAnonymization(
    request: UserRef,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  startAccountAnonymization(
    request: UserRef,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SagaHandle) => void,
  ): ClientUnaryCall;
  /**
   * Aprobación de una calculadora al catálogo público (FR-053).
   *
   * Va por el Orquestador y no directo al Simulador por el mismo motivo que
   * `StartSimulation`: el Simulador NO es productor de eventos (Principio V) y la
   * aprobación tiene que quedar auditada. `calculator.published` es el rastro de quién
   * aprobó qué versión y cuándo, y sin él una calculadora aparecería en el catálogo sin
   * que nada diga cómo llegó.
   *
   * SÍNCRONA, como `StartSimulation`, y no un `SagaHandle`: el coordinador está esperando
   * el resultado de un clic, y devolverle un identificador de saga al que después preguntar
   * añadiría una consulta para una operación que dura una llamada.
   */
  approveCalculator(
    request: CalculatorApprovalRequest,
    callback: (error: ServiceError | null, response: CalculatorApprovalResult) => void,
  ): ClientUnaryCall;
  approveCalculator(
    request: CalculatorApprovalRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CalculatorApprovalResult) => void,
  ): ClientUnaryCall;
  approveCalculator(
    request: CalculatorApprovalRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CalculatorApprovalResult) => void,
  ): ClientUnaryCall;
  /** Consulta de estado de una saga. */
  getSagaStatus(
    request: SagaHandle,
    callback: (error: ServiceError | null, response: SagaStatus) => void,
  ): ClientUnaryCall;
  getSagaStatus(
    request: SagaHandle,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SagaStatus) => void,
  ): ClientUnaryCall;
  getSagaStatus(
    request: SagaHandle,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SagaStatus) => void,
  ): ClientUnaryCall;
}

export const OrchestratorServiceClient = makeGenericClientConstructor(
  OrchestratorServiceService,
  "fintcart.orchestrator.v1.OrchestratorService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): OrchestratorServiceClient;
  service: typeof OrchestratorServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
