// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: fintcart/common/v1/common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'fintcart.common.v1';

/** Dinero: monto decimal + código ISO-4217 (por defecto COP). */
export interface Money {
  /** [decimal] p. ej. "1500000.00" */
  amount: string;
  /** p. ej. "COP" */
  currency: string;
}

/** Paginación estándar para listados de solo lectura. */
export interface PageRequest {
  page_size: number;
  page_token: string;
}

export interface PageResponse {
  next_page_token: string;
  total_size: string;
}

/** Marca temporal en RFC-3339 UTC como string para evitar ambigüedad de zona. */
export interface Timestamp {
  /** p. ej. "2026-06-13T15:04:05Z" */
  rfc3339: string;
}

/** Resultado genérico de una operación de comando. */
export interface OpResult {
  success: boolean;
  /** código de error de dominio si aplica */
  code: string;
  message: string;
}

function createBaseMoney(): Money {
  return { amount: '', currency: '' };
}

export const Money: MessageFns<Money> = {
  encode(message: Money, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== '') {
      writer.uint32(10).string(message.amount);
    }
    if (message.currency !== '') {
      writer.uint32(18).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Money {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoney();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Money {
    return {
      amount: isSet(object.amount) ? globalThis.String(object.amount) : '',
      currency: isSet(object.currency) ? globalThis.String(object.currency) : '',
    };
  },

  toJSON(message: Money): unknown {
    const obj: any = {};
    if (message.amount !== '') {
      obj.amount = message.amount;
    }
    if (message.currency !== '') {
      obj.currency = message.currency;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Money>, I>>(base?: I): Money {
    return Money.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Money>, I>>(object: I): Money {
    const message = createBaseMoney();
    message.amount = object.amount ?? '';
    message.currency = object.currency ?? '';
    return message;
  },
};

function createBasePageRequest(): PageRequest {
  return { page_size: 0, page_token: '' };
}

export const PageRequest: MessageFns<PageRequest> = {
  encode(message: PageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page_size !== 0) {
      writer.uint32(8).int32(message.page_size);
    }
    if (message.page_token !== '') {
      writer.uint32(18).string(message.page_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page_size = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.page_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PageRequest {
    return {
      page_size: isSet(object.page_size) ? globalThis.Number(object.page_size) : 0,
      page_token: isSet(object.page_token) ? globalThis.String(object.page_token) : '',
    };
  },

  toJSON(message: PageRequest): unknown {
    const obj: any = {};
    if (message.page_size !== 0) {
      obj.page_size = Math.round(message.page_size);
    }
    if (message.page_token !== '') {
      obj.page_token = message.page_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PageRequest>, I>>(base?: I): PageRequest {
    return PageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PageRequest>, I>>(object: I): PageRequest {
    const message = createBasePageRequest();
    message.page_size = object.page_size ?? 0;
    message.page_token = object.page_token ?? '';
    return message;
  },
};

function createBasePageResponse(): PageResponse {
  return { next_page_token: '', total_size: '0' };
}

export const PageResponse: MessageFns<PageResponse> = {
  encode(message: PageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.next_page_token !== '') {
      writer.uint32(10).string(message.next_page_token);
    }
    if (message.total_size !== '0') {
      writer.uint32(16).int64(message.total_size);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.next_page_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total_size = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PageResponse {
    return {
      next_page_token: isSet(object.next_page_token)
        ? globalThis.String(object.next_page_token)
        : '',
      total_size: isSet(object.total_size) ? globalThis.String(object.total_size) : '0',
    };
  },

  toJSON(message: PageResponse): unknown {
    const obj: any = {};
    if (message.next_page_token !== '') {
      obj.next_page_token = message.next_page_token;
    }
    if (message.total_size !== '0') {
      obj.total_size = message.total_size;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PageResponse>, I>>(base?: I): PageResponse {
    return PageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PageResponse>, I>>(object: I): PageResponse {
    const message = createBasePageResponse();
    message.next_page_token = object.next_page_token ?? '';
    message.total_size = object.total_size ?? '0';
    return message;
  },
};

function createBaseTimestamp(): Timestamp {
  return { rfc3339: '' };
}

export const Timestamp: MessageFns<Timestamp> = {
  encode(message: Timestamp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rfc3339 !== '') {
      writer.uint32(10).string(message.rfc3339);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Timestamp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTimestamp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rfc3339 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Timestamp {
    return { rfc3339: isSet(object.rfc3339) ? globalThis.String(object.rfc3339) : '' };
  },

  toJSON(message: Timestamp): unknown {
    const obj: any = {};
    if (message.rfc3339 !== '') {
      obj.rfc3339 = message.rfc3339;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Timestamp>, I>>(base?: I): Timestamp {
    return Timestamp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Timestamp>, I>>(object: I): Timestamp {
    const message = createBaseTimestamp();
    message.rfc3339 = object.rfc3339 ?? '';
    return message;
  },
};

function createBaseOpResult(): OpResult {
  return { success: false, code: '', message: '' };
}

export const OpResult: MessageFns<OpResult> = {
  encode(message: OpResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.code !== '') {
      writer.uint32(18).string(message.code);
    }
    if (message.message !== '') {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OpResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      code: isSet(object.code) ? globalThis.String(object.code) : '',
      message: isSet(object.message) ? globalThis.String(object.message) : '',
    };
  },

  toJSON(message: OpResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.code !== '') {
      obj.code = message.code;
    }
    if (message.message !== '') {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OpResult>, I>>(base?: I): OpResult {
    return OpResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OpResult>, I>>(object: I): OpResult {
    const message = createBaseOpResult();
    message.success = object.success ?? false;
    message.code = object.code ?? '';
    message.message = object.message ?? '';
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
